In [1]:
# Upload libraries
library(readr)
library(dplyr)
library(stringr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
setwd("/mnt/l/colon1_hmmer_backup/")

In [3]:
#get unique species

all_gtdbtk_bac120_summary_colon01 <- read_delim("GTDB_results/gtdbtk.bac120.summary.tsv", 
                                            delim = "\t", escape_double = FALSE, 
                                            trim_ws = TRUE)
head(all_gtdbtk_bac120_summary_colon01)

Rows: 23 Columns: 20
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (20): user_genome, classification, closest_genome_reference, closest_gen...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR478963_bin.7
2 ERR478973_bin.12
3 ERR478985_bin.9
4 ERR479006_bin.4
5 ERR479009_bin.11
6 ERR479042_bin.7
  classification
1 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Roseburia;s__Roseburia intestinalis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
4 Unclassified Bacteria
5 Unclassified
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__
  closest_genome_reference closest_genome_reference_radius
1 N/A                      N/A
2 GCF_900537995.1          95.0
3 GCF_040096305.1          95.12
4 N/A                      N/A
5 N/A                      N/A
6 N/A                      N/A
  closest_genome_taxonomy
1 N/A
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Roseburia;s__Roseburia intestinalis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
4 N/A
5 N/A
6 N/A
  closest_genome_ani closest_genome_af closest_placement_reference
1 N/A                N/A               N/A
2 98.84              0.543             N/A
3 97.93              0.729             N/A
4 N/A                N/A               N/A
5 N/A                N/A               N/A
6 N/A                N/A               N/A
  closest_placement_radius closest_placement_taxonomy closest_placement_ani
1 N/A                      N/A                        N/A
2 N/A                      N/A                        N/A
3 N/A                      N/A                        N/A
4 N/A                      N/A                        N/A
5 N/A                      N/A                        N/A
6 N/A                      N/A                        N/A
  closest_placement_af
1 N/A
2 N/A
3 N/A
4 N/A
5 N/A
6 N/A
  pplacer_taxonomy
1 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__
2 N/A
3 N/A
4 N/A
5 N/A
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__
  classification_method
1 taxonomic classification defined by topology and ANI
2 ani_screen
3 ani_screen
4 N/A
5 N/A
6 taxonomic classification fully defined by topology
  note
1 classification based on placement in class-level tree
2 classification based on ANI only
3 classification based on ANI only
4 N/A
5 N/A
6 classification based on placement in class-level tree
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCA_019414725.1, s__Phocaeicola sp019414725, 95.0, 99.54, 0.152; GCA_019414665.1, s__Phocaeicola sp019414665, 95.0, 99.2, 0.193; GCA_900760795.1, s__Phocaeicola sp900760795, 95.0, 99.17, 0.307; GCF_964248265.1, s__Phocaeicola vulgatus, 95.21, 98.91, 0.324; GCA_948579315.1, s__Phocaeicola sp948579315, 95.0, 98.86, 0.205; GCA_948566455.1, s__Phocaeicola sp948566455, 95.0, 98.75, 0.209; GCA_947574505.1, s__Phocaeicola sp947574505, 95.0, 98.7, 0.214; GCF_000382445.1, s__Phocaeicola massiliensis, 95.0, 98.03, 0.156; GCF_013009555.1, s__Phocaeicola dorei, 95.0, 95.89, 0.276; GCF_024622025.1, s__Phocaeicola sartorii, 95.0, 90.57, 0.154; GCA_947072895.1, s__Phocaeicola sp011959205, 95.0, 90.51, 0.164
2 GCA_002474415.1, s__Agathobacter sp002474415, 95.0, 90.95, 0.429; GCF_014287515.2, s__Roseburia rectibacter, 95.0, 91.22, 0.357; GCA_003483745.1, s__Roseburia sp003483745, 95.0, 91.5, 0.409; GCA_934317215.1, s__Roseburia sp934317215, 95.0, 94.34, 0.525; GCF_001406815.1, s__Agathobacter faecis, 95.0, 98.42, 0.637
3 GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 92.45, 0.494; GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 95.3, 0.644; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 90.8, 0.438; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 94.6, 0.583
4 N/A
5 N/A
6 N/A
  msa_percent translation_table red_value
1 34.65       11                0.97646
2 N/A         N/A               N/A
3 N/A         N/A               N/A
4 N/A         N/A               N/A
5 N/A         N/A               N/A
6 11.34       11                0.92677
  warnings
1 Genome has more than 13.3% of markers with multiple hits
2 N/A
3 N/A
4 Insufficient number of amino acids in MSA (2.4%)
5 No bacterial or archaeal marker
6 N/A

In [4]:
# Upload result of checkm filtering

checkm_summary_colon01 <- read_delim("quality_report_bin_filtered_ID.tsv",
                                     delim = "\t", escape_double = FALSE, 
                                     trim_ws = TRUE, col_names = "user_genome")
head(checkm_summary_colon01)

Rows: 5 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): user_genome

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR479145_bin.10
2 ERR479080_bin.12
3 ERR479070_bin.26
4 ERR478985_bin.9
5 ERR479195_bin.21

In [6]:
# Filter ID based on checkm result
gtdbtk_bac120_summary_colon01 <- semi_join(all_gtdbtk_bac120_summary_colon01, checkm_summary_colon01, by= "user_genome")
nrow(gtdbtk_bac120_summary_colon01)

[1] 5

In [7]:
#get species name
gtdbtk_classify_colon01 <- gtdbtk_bac120_summary_colon01[,"classification"]

gtdbtk_species_colon01 <- gtdbtk_classify_colon01 %>%
  mutate(species = str_extract(classification, "(?<=s__).*"))

gtdbtk_species_colon01$species <- trimws(gtdbtk_species_colon01$species)
gtdbtk_species_colon01$species[gtdbtk_species_colon01$species == ""] <- NA

unique(gtdbtk_species_colon01$species)

[1] "Ruminococcoides intestinale" "Gemmiger formicilis"
[3] "Anaerobutyricum hallii"      "Phocaeicola vulgatus"

In [8]:
#count species match
table(gtdbtk_species_colon01$species)

count_gtdb_colon01 <- gtdbtk_species_colon01 %>%
  count(species, name = "occurrences")

head(count_gtdb_colon01)
sum(count_gtdb_colon01$occurrences)

unique_gtdbtk_species_colon01 <- gtdbtk_species_colon01 %>% distinct(species, .keep_all = TRUE)

unique_gtdbtk_species_colon01_ID <- unique_gtdbtk_species_colon01[,"species"]

     Anaerobutyricum hallii         Gemmiger formicilis
                          1                           1
       Phocaeicola vulgatus Ruminococcoides intestinale
                          1                           2

  species                     occurrences
1 Anaerobutyricum hallii      1
2 Gemmiger formicilis         1
3 Phocaeicola vulgatus        1
4 Ruminococcoides intestinale 2

[1] 5

In [ ]:
write_tsv(unique_gtdbtk_species_colon01_ID, "GTDB_results/unique_gtdbtk_species_colon01_ID.tsv")

In [12]:
################################################################################################################
#Division of disease versus Healthy


# Remove everything after the first "-"
gtdbtk_bac120_summary_colon01$ID <- sub("_.*", "", gtdbtk_bac120_summary_colon01$user_genome)

#get ID
gtdbtk_colon01_ID_name <- gtdbtk_bac120_summary_colon01[,"ID"]

In [ ]:
#save file
write_tsv(gtdbtk_colon01_ID_name, "GTDB_results/gtdbtk_colon01_ERR_ID_name.tsv")

In [13]:
#Upload data with health and disease ID

#case
Study_1_cancer_case_Run_ID <- read_tsv("all_cancer_FR_get_ID.tsv")

head(Study_1_cancer_case_Run_ID)

Rows: 512 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR479054
2 ERR480549
3 ERR479053
4 ERR479055
5 ERR480550
6 ERR480551

In [14]:
#control

Study_1_cancer_control_Run_ID <- read_tsv("france_normal_get_ID.tsv")
head(Study_1_cancer_control_Run_ID)

Rows: 410 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR479092
2 ERR480587
3 ERR480588
4 ERR479091
5 ERR479036
6 ERR479033

In [15]:
#match and see how many match
colnames(gtdbtk_colon01_ID_name) <- "Run"

#for case
match_colon01_case <- semi_join(gtdbtk_colon01_ID_name,Study_1_cancer_case_Run_ID, by= "Run")
nrow(match_colon01_case)

#get unique IDs
match_colon01_case_unique <- match_colon01_case %>% distinct(Run)
nrow(match_colon01_case_unique)

[1] 3

[1] 3

In [16]:
#for control
match_colon01_control <- semi_join(gtdbtk_colon01_ID_name,Study_1_cancer_control_Run_ID, by= "Run")
nrow(match_colon01_control)
#get unique IDs

match_colon01_control_unique <- match_colon01_control %>% distinct(Run)
nrow(match_colon01_control_unique)

[1] 2

[1] 2

In [17]:
#Final table 

cat_gtdk_ID <- merge(gtdbtk_bac120_summary_colon01,gtdbtk_species_colon01, by="classification")

cat_gtdk_ID_col <- cat_gtdk_ID[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species")]
head(cat_gtdk_ID)
nrow(cat_gtdk_ID)

  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
  user_genome      closest_genome_reference closest_genome_reference_radius
1 ERR479080_bin.12 GCF_000173975.1          95.0
2 ERR478985_bin.9  GCF_040096305.1          95.12
3 ERR478985_bin.9  GCF_040096305.1          95.12
4 ERR479145_bin.10 GCF_040096305.1          95.12
5 ERR479145_bin.10 GCF_040096305.1          95.12
6 ERR479070_bin.26 GCF_900167555.1          95.0
  closest_genome_taxonomy
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.86              0.804             N/A
2 97.93              0.729             N/A
3 97.93              0.729             N/A
4 98.14              0.875             N/A
5 98.14              0.875             N/A
6 97.79              0.906             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
6 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
6 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCF_900209925.1, s__Anaerobutyricum soehngenii, 95.0, 87.46, 0.187; GCA_963600375.1, s__Anaerobutyricum sp963600375, 95.0, 86.85, 0.228; GCF_934307085.1, s__Anaerobutyricum sp934307085, 95.0, 89.42, 0.359
2 GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 92.45, 0.494; GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 95.3, 0.644; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 90.8, 0.438; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 94.6, 0.583
3 GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 92.45, 0.494; GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 95.3, 0.644; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 90.8, 0.438; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 94.6, 0.583
4 GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 94.44, 0.811; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 89.54, 0.58; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 93.87, 0.748; GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 91.75, 0.622
5 GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 94.44, 0.811; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 89.54, 0.58; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 93.87, 0.748; GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 91.75, 0.622
6 GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 88.96, 0.346; GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 89.25, 0.357; GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 87.63, 0.232; GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 89.56, 0.257
  msa_percent translation_table red_value warnings ID
1 N/A         N/A               N/A       N/A      ERR479080
2 N/A         N/A               N/A       N/A      ERR478985
3 N/A         N/A               N/A       N/A      ERR478985
4 N/A         N/A               N/A       N/A      ERR479145
5 N/A         N/A               N/A       N/A      ERR479145
6 N/A         N/A               N/A       N/A      ERR479070
  species
1 Anaerobutyricum hallii
2 Ruminococcoides intestinale
3 Ruminococcoides intestinale
4 Ruminococcoides intestinale
5 Ruminococcoides intestinale
6 Gemmiger formicilis

[1] 7

In [19]:
cat_gtdk_ID_unique <- cat_gtdk_ID%>% distinct(user_genome,.keep_all=TRUE)
nrow(cat_gtdk_ID_unique)
head(cat_gtdk_ID_unique)

[1] 5

  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola vulgatus
  user_genome      closest_genome_reference closest_genome_reference_radius
1 ERR479080_bin.12 GCF_000173975.1          95.0
2 ERR478985_bin.9  GCF_040096305.1          95.12
3 ERR479145_bin.10 GCF_040096305.1          95.12
4 ERR479070_bin.26 GCF_900167555.1          95.0
5 ERR479195_bin.21 GCF_964248265.1          95.21
  closest_genome_taxonomy
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola vulgatus
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.86              0.804             N/A
2 97.93              0.729             N/A
3 98.14              0.875             N/A
4 97.79              0.906             N/A
5 99.12              0.823             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCF_900209925.1, s__Anaerobutyricum soehngenii, 95.0, 87.46, 0.187; GCA_963600375.1, s__Anaerobutyricum sp963600375, 95.0, 86.85, 0.228; GCF_934307085.1, s__Anaerobutyricum sp934307085, 95.0, 89.42, 0.359
2 GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 92.45, 0.494; GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 95.3, 0.644; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 90.8, 0.438; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 94.6, 0.583
3 GCF_002834225.1, s__Ruminococcoides bromii, 95.0, 94.44, 0.811; GCA_902766775.1, s__Ruminococcoides sp902766775, 95.0, 89.54, 0.58; GCA_905215855.1, s__Ruminococcoides sp905215855, 95.0, 93.87, 0.748; GCA_902771755.1, s__Ruminococcoides sp902771755, 95.0, 91.75, 0.622
4 GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 88.96, 0.346; GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 89.25, 0.357; GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 87.63, 0.232; GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 89.56, 0.257
5 GCA_963651205.1, s__Phocaeicola sp963651205, 95.0, 86.92, 0.289; GCA_947072895.1, s__Phocaeicola sp011959205, 95.0, 89.85, 0.448; GCF_013009555.1, s__Phocaeicola dorei, 95.0, 95.8, 0.75; GCA_900760795.1, s__Phocaeicola sp900760795, 95.0, 95.98, 0.431; GCA_019414725.1, s__Phocaeicola sp019414725, 95.0, 98.44, 0.376; GCA_958432865.1, s__Bacteroides stercoris_A, 95.0, 98.18, 0.323; GCA_948579315.1, s__Phocaeicola sp948579315, 95.0, 98.79, 0.356; GCA_948566455.1, s__Phocaeicola sp948566455, 95.0, 99.18, 0.352; GCA_947574505.1, s__Phocaeicola sp947574505, 95.0, 98.24, 0.341; GCF_024622025.1, s__Phocaeicola sartorii, 95.0, 90.46, 0.511; GCA_019414665.1, s__Phocaeicola sp019414665, 95.0, 99.15, 0.382
  msa_percent translation_table red_value warnings ID
1 N/A         N/A               N/A       N/A      ERR479080
2 N/A         N/A               N/A       N/A      ERR478985
3 N/A         N/A               N/A       N/A      ERR479145
4 N/A         N/A               N/A       N/A      ERR479070
5 N/A         N/A               N/A       N/A      ERR479195
  species
1 Anaerobutyricum hallii
2 Ruminococcoides intestinale
3 Ruminococcoides intestinale
4 Gemmiger formicilis
5 Phocaeicola vulgatus

In [20]:
cat_gtdk_ID_col <- cat_gtdk_ID_unique[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species", "user_genome")]


cat_colon01_preview <- merge(cat_gtdk_ID_col,count_gtdb_colon01, by= "species")
head(cat_colon01_preview)

  species
1 Anaerobutyricum hallii
2 Gemmiger formicilis
3 Phocaeicola vulgatus
4 Ruminococcoides intestinale
5 Ruminococcoides intestinale
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola vulgatus
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
  closest_genome_reference closest_genome_ani ID        user_genome
1 GCF_000173975.1          98.86              ERR479080 ERR479080_bin.12
2 GCF_900167555.1          97.79              ERR479070 ERR479070_bin.26
3 GCF_964248265.1          99.12              ERR479195 ERR479195_bin.21
4 GCF_040096305.1          97.93              ERR478985 ERR478985_bin.9
5 GCF_040096305.1          98.14              ERR479145 ERR479145_bin.10
  occurrences
1 1
2 1
3 1
4 2
5 2

In [21]:
# handling with control and disease column

match_colon01_control$State <- "Control"
match_colon01_case$State <- "Disease"

# Change column name

colnames(match_colon01_control)[colnames(match_colon01_control) == "Run"] <- "ID"
colnames(match_colon01_case)[colnames(match_colon01_case) == "Run"] <- "ID" 

all_state <- rbind(match_colon01_control,match_colon01_case)

cat_colon01_final <- merge(cat_colon01_preview,all_state, by= "ID")
head(cat_colon01_final)
nrow(cat_colon01_final)

  ID        species
1 ERR478985 Ruminococcoides intestinale
2 ERR479070 Gemmiger formicilis
3 ERR479080 Anaerobutyricum hallii
4 ERR479145 Ruminococcoides intestinale
5 ERR479195 Phocaeicola vulgatus
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola vulgatus
  closest_genome_reference closest_genome_ani user_genome      occurrences
1 GCF_040096305.1          97.93              ERR478985_bin.9  2
2 GCF_900167555.1          97.79              ERR479070_bin.26 1
3 GCF_000173975.1          98.86              ERR479080_bin.12 1
4 GCF_040096305.1          98.14              ERR479145_bin.10 2
5 GCF_964248265.1          99.12              ERR479195_bin.21 1
  State
1 Disease
2 Disease
3 Control
4 Disease
5 Control

[1] 5

In [23]:
cat_colon01_final_end <- cat_colon01_final %>% distinct(user_genome, .keep_all = TRUE)
head(cat_colon01_final_end)

  ID        species
1 ERR478985 Ruminococcoides intestinale
2 ERR479070 Gemmiger formicilis
3 ERR479080 Anaerobutyricum hallii
4 ERR479145 Ruminococcoides intestinale
5 ERR479195 Phocaeicola vulgatus
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola vulgatus
  closest_genome_reference closest_genome_ani user_genome      occurrences
1 GCF_040096305.1          97.93              ERR478985_bin.9  2
2 GCF_900167555.1          97.79              ERR479070_bin.26 1
3 GCF_000173975.1          98.86              ERR479080_bin.12 1
4 GCF_040096305.1          98.14              ERR479145_bin.10 2
5 GCF_964248265.1          99.12              ERR479195_bin.21 1
  State
1 Disease
2 Disease
3 Control
4 Disease
5 Control

In [ ]:
#save output
write_tsv(cat_colon01_final_end, "GTDB_results/final_table_gtdb_for_paper_colon01.tsv")
write_tsv(count_gtdb_colon01, "GTDB_results/species_occurrence.tsv")

In [24]:
# Classify species
classification <- cat_colon01_final_end %>%
  filter(!is.na(species), !is.na(State)) %>%
  group_by(species) %>%
  summarise(
    Group_classification = case_when(
      n_distinct(State) == 1 & first(State) == "Disease" ~ "Disease",
      n_distinct(State) == 1 & first(State) == "Control" ~ "Control",
      n_distinct(State) > 1 ~ "Control/Disease"
    ),
    .groups = "drop"
  )

# Join  and apply rule for Species == NA
cat_colon01_final_end_df <- cat_colon01_final_end %>%
  left_join(classification, by = "species") %>%
  mutate(
    Group_classification = ifelse(
      is.na(species),
      State,
      Group_classification
    )
  )

head(cat_colon01_final_end_df)
nrow(cat_colon01_final_end_df)

  ID        species
1 ERR478985 Ruminococcoides intestinale
2 ERR479070 Gemmiger formicilis
3 ERR479080 Anaerobutyricum hallii
4 ERR479145 Ruminococcoides intestinale
5 ERR479195 Phocaeicola vulgatus
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerobutyricum;s__Anaerobutyricum hallii
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Ruminococcoides;s__Ruminococcoides intestinale
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Phocaeicola;s__Phocaeicola vulgatus
  closest_genome_reference closest_genome_ani user_genome      occurrences
1 GCF_040096305.1          97.93              ERR478985_bin.9  2
2 GCF_900167555.1          97.79              ERR479070_bin.26 1
3 GCF_000173975.1          98.86              ERR479080_bin.12 1
4 GCF_040096305.1          98.14              ERR479145_bin.10 2
5 GCF_964248265.1          99.12              ERR479195_bin.21 1
  State   Group_classification
1 Disease Disease
2 Disease Disease
3 Control Control
4 Disease Disease
5 Control Control

[1] 5

In [ ]:
write_tsv(cat_colon01_final_end_df,"L:/colon1_hmmer_backup/GTDB_results/gtdb_final_table_with_condition_colon01_corrigido.tsv")

In [25]:
cat_colon01_final_end_df_col <- cat_colon01_final_end_df[ ,c("species", "occurrences", "Group_classification")]

cat_colon01_final_end_df_col_unique <- cat_colon01_final_end_df_col %>% distinct(species, .keep_all = TRUE)
head(cat_colon01_final_end_df_col_unique)
nrow(cat_colon01_final_end_df_col_unique)

  species                     occurrences Group_classification
1 Ruminococcoides intestinale 2           Disease
2 Gemmiger formicilis         1           Disease
3 Anaerobutyricum hallii      1           Control
4 Phocaeicola vulgatus        1           Control

[1] 4

In [ ]:
#Save output for paper 
write_tsv(cat_colon01_final_end_df_col_unique, "L:/colon1_hmmer_backup/GTDB_results/count_ocurrence_w_condition_for_paper_colon01.tsv")