In [1]:
#Upload libraries
library(readr)
library(dplyr)
library(stringr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
setwd("/mnt/l/colon3_hmmer_backup/")

In [3]:
#get unique species

all_gtdbtk_bac120_summary_colon03 <- read_delim("all_colon03_summ_gtdb_arch_bac.tsv", 
                                                delim = "\t", escape_double = FALSE, 
                                                trim_ws = TRUE)
head(all_gtdbtk_bac120_summary_colon03)

Rows: 364 Columns: 20
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (20): user_genome, classification, closest_genome_reference, closest_gen...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR688505_31004_SZAXPI021650-108_bin.2
2 ERR688505_31004_SZAXPI021650-108_bin.3
3 ERR688505_31004_SZAXPI021650-108_bin.37
4 ERR688506_31009_SZAXPI022053-133_bin.16
5 ERR688506_31009_SZAXPI022053-133_bin.20
6 ERR688506_31009_SZAXPI022053-133_bin.27
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger qucibialis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 Unclassified Bacteria
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Fusicatenibacter;s__Fusicatenibacter saccharivorans
  closest_genome_reference closest_genome_reference_radius
1 GCA_025758045.1          95.0
2 GCA_004000625.1          95.0
3 GCF_900167555.1          95.0
4 N/A                      N/A
5 GCF_900167555.1          95.0
6 GCF_027667425.1          95.0
  closest_genome_taxonomy
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger qucibialis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 N/A
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Fusicatenibacter;s__Fusicatenibacter saccharivorans
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.68              0.92              N/A
2 98.61              0.831             N/A
3 98.07              0.851             N/A
4 N/A                N/A               N/A
5 97.93              0.925             N/A
6 97.42              0.828             N/A
  closest_placement_radius closest_placement_taxonomy closest_placement_ani
1 N/A                      N/A                        N/A
2 N/A                      N/A                        N/A
3 N/A                      N/A                        N/A
4 N/A                      N/A                        N/A
5 N/A                      N/A                        N/A
6 N/A                      N/A                        N/A
  closest_placement_af pplacer_taxonomy classification_method
1 N/A                  N/A              ani_screen
2 N/A                  N/A              ani_screen
3 N/A                  N/A              ani_screen
4 N/A                  N/A              N/A
5 N/A                  N/A              ani_screen
6 N/A                  N/A              ani_screen
  note
1 classification based on ANI only
2 classification based on ANI only
3 classification based on ANI only
4 N/A
5 classification based on ANI only
6 classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCA_004554775.1, s__Gemmiger variabilis_B, 95.0, 88.34, 0.496; GCA_963588145.1, s__Gemmiger sp963588145, 95.0, 89.42, 0.512; GCA_963655125.1, s__Gemmiger sp963655125, 95.0, 90.76, 0.615
2 GCA_963626055.1, s__Gemmiger sp963626055, 95.0, 93.41, 0.722
3 GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 86.91, 0.321; GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 86.98, 0.378; GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 84.88, 0.243; GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 86.96, 0.385
4 N/A
5 GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 89.65, 0.243; GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 89.48, 0.303; GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 89.3, 0.245; GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 88.57, 0.159
6 GCA_963661155.1, s__Fusicatenibacter massiliensis_A, 95.0, 89.21, 0.368; GCA_963596755.1, s__Fusicatenibacter sp963596755, 95.0, 90.12, 0.402; GCA_900772675.1, s__Fusicatenibacter sp900772675, 95.0, 91.95, 0.246
  msa_percent translation_table red_value
1 N/A         N/A               N/A
2 N/A         N/A               N/A
3 N/A         N/A               N/A
4 N/A         N/A               N/A
5 N/A         N/A               N/A
6 N/A         N/A               N/A
  warnings
1 N/A
2 N/A
3 N/A
4 Insufficient number of amino acids in MSA (3.3%)
5 N/A
6 N/A

In [5]:
# Upload result of checkm filtering

checkm_summary_colon03 <- read_delim("quality_report_bin_filtered_ID.tsv",
                                     delim = "\t", escape_double = FALSE, 
                                     trim_ws = TRUE, col_names = "user_genome")

head(checkm_summary_colon03)
# Filter ID based on checkm result
gtdbtk_bac120_summary_colon03 <- semi_join(all_gtdbtk_bac120_summary_colon03, checkm_summary_colon03, by= "user_genome")

Rows: 283 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): user_genome

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR688506_31009_SZAXPI022053-133_bin.27
2 ERR688506_31009_SZAXPI022053-133_bin.50
3 ERR688506_31009_SZAXPI022053-133_bin.57
4 ERR688507_31021_SZAXPI022043-90_bin.49
5 ERR688505_31004_SZAXPI021650-108_bin.3
6 ERR688509_31071_SZAXPI022073-62_bin.25

In [6]:
#get species name
gtdbtk_classify_colon03 <- gtdbtk_bac120_summary_colon03[,"classification"]

gtdbtk_species_colon03 <- gtdbtk_classify_colon03 %>%
  mutate(species = str_extract(classification, "(?<=s__).*"))

gtdbtk_species_colon03$species <- trimws(gtdbtk_species_colon03$species)
gtdbtk_species_colon03$species[gtdbtk_species_colon03$species == ""] <- NA

unique(gtdbtk_species_colon03$species)

#count species match
table(gtdbtk_species_colon03$species)

 [1] "Gemmiger sp900539695"            "Gemmiger qucibialis"
 [3] "Gemmiger formicilis"             "Fusicatenibacter saccharivorans"
 [5] "Bacteroides_F pectinophilus"     "Alistipes onderdonkii"
 [7] "Gemmiger sp900540775"            "Agathobacter rectalis"
 [9] "Ruminiclostridium_E sp003512525" "Gemmiger sp900540595"
[11] "Anaerostipes sp900066705"        "Anaerotardibacter sp000435675"
[13] "Anaerostipes hadrus"             "Anaerobutyricum soehngenii"
[15] "Phocaeicola dorei"               "CAG-194 sp000432915"
[17] "Acutalibacter ornithocaccae"     "Anaerobutyricum hallii"
[19] "Anaerostipes sp019423795"        "Blautia_A acetigignens"
[21] "Eubacterium_G ventriosum"        "Romboutsia timonensis"
[23] "Ruminiclostridium_E sp900539195" "Maccoya intestinihominis"
[25] "Mediterraneibacter faecis"       "Egerieenecus merdigallinarum"
[27] "Gemmiger stercoripullorum"       "Adlercreutzia rubneri"
[29] "Dorea_D sp900543415"             "Alistipes sp900541585"
[31] "Alistipes finegoldii"            "Ruminococcoides intestinale"
[33] "Acetatifactor acetigignens"      "Alistipes shahii"
[35] "Ruminococcoides intestinalis"    "Acutalibacter stercoravium"
[37] "Alistipes avistercoris"          "UBA2882 sp900542015"
[39] "Phocaeicola vulgatus"            "Parabacteroides distasonis"
[41] "Phascolarctobacterium faecium"   "Turicibacter bilis"
[43] "Eubacterium_G segne"             "Methanocatella smithii_A"
[45] "Methanocatella smithii"

     Acetatifactor acetigignens     Acutalibacter ornithocaccae
                              1                               3
     Acutalibacter stercoravium           Adlercreutzia rubneri
                              1                               1
          Agathobacter rectalis          Alistipes avistercoris
                              4                               2
           Alistipes finegoldii           Alistipes onderdonkii
                              5                              22
               Alistipes shahii           Alistipes sp900541585
                              4                               1
         Anaerobutyricum hallii      Anaerobutyricum soehngenii
                              1                               1
            Anaerostipes hadrus        Anaerostipes sp019423795
                              2                               1
       Anaerostipes sp900066705   Anaerotardibacter sp000435675
                              2                               3
    Bacteroides_F pectinophilus          Blautia_A acetigignens
                              1                               2
            CAG-194 sp000432915             Dorea_D sp900543415
                              2                               1
   Egerieenecus merdigallinarum             Eubacterium_G segne
                              1                               1
       Eubacterium_G ventriosum Fusicatenibacter saccharivorans
                              1                               3
            Gemmiger formicilis             Gemmiger qucibialis
                             61                              80
           Gemmiger sp900539695            Gemmiger sp900540595
                             20                               4
           Gemmiger sp900540775       Gemmiger stercoripullorum
                             14                               1
       Maccoya intestinihominis       Mediterraneibacter faecis
                              1                               2
         Methanocatella smithii        Methanocatella smithii_A
                              4                              13
     Parabacteroides distasonis   Phascolarctobacterium faecium
                              3                               1
              Phocaeicola dorei            Phocaeicola vulgatus
                              2                               1
          Romboutsia timonensis Ruminiclostridium_E sp003512525
                              2                               1
Ruminiclostridium_E sp900539195     Ruminococcoides intestinale
                              1                               3
   Ruminococcoides intestinalis              Turicibacter bilis
                              1                               1
            UBA2882 sp900542015
                              1

In [7]:
count_gtdb_colon03 <- gtdbtk_species_colon03 %>%
  count(species, name = "occurrences")

head(count_gtdb_colon03)


unique_gtdbtk_species_colon03 <- gtdbtk_species_colon03 %>% distinct(species, .keep_all = TRUE)

unique_gtdbtk_species_colon03_ID <- unique_gtdbtk_species_colon03[,"species"]

  species                     occurrences
1 Acetatifactor acetigignens  1
2 Acutalibacter ornithocaccae 3
3 Acutalibacter stercoravium  1
4 Adlercreutzia rubneri       1
5 Agathobacter rectalis       4
6 Alistipes avistercoris      2

In [ ]:
#Save output
write_tsv(unique_gtdbtk_species_colon03_ID, "GTDB_results/unique_gtdbtk_species_colon03_ID.tsv")

In [8]:
################################################################################################################
#Division of disease versus Healthy


# Remove everything after the first "-"
gtdbtk_bac120_summary_colon03$ID <- sub("_.*", "", gtdbtk_bac120_summary_colon03$user_genome)

#get ID
gtdbtk_colon03_ID_name <- gtdbtk_bac120_summary_colon03[,"ID"]

In [ ]:
#save file
write_tsv(gtdbtk_colon03_ID_name, "GTDB_results/gtdbtk_colon03_ERR_ID_name.tsv")

In [9]:
#Upload data with health and disease ID

#case
Study_3_cancer_case_Run_ID <- read_csv("all_cancer_study3_ID")

head(Study_3_cancer_case_Run_ID)

Rows: 187 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR688389
2 ERR688536
3 ERR688498
4 ERR688645
5 ERR688454
6 ERR688601

In [10]:
#control

Study_3_cancer_control_Run_ID <- read_csv("all_control_study3_ID.tsv")
head(Study_3_cancer_control_Run_ID)

Rows: 126 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR688419
2 ERR688566
3 ERR688405
4 ERR688552
5 ERR688409
6 ERR688556

In [11]:
#match and see how many match
colnames(gtdbtk_colon03_ID_name) <- "Run"

#for case
match_colon03_case <- semi_join(gtdbtk_colon03_ID_name,Study_3_cancer_case_Run_ID, by= "Run")
nrow(match_colon03_case)

#get unique IDs
match_colon03_case_unique <- match_colon03_case %>% distinct(Run)
nrow(match_colon03_case_unique)

[1] 175

[1] 73

In [12]:
#for control
match_colon03_control <- semi_join(gtdbtk_colon03_ID_name,Study_3_cancer_control_Run_ID, by= "Run")
nrow(match_colon03_control)
#get unique IDs

match_colon03_control_unique <- match_colon03_control %>% distinct(Run)
nrow(match_colon03_control_unique)

[1] 108

[1] 43

In [13]:
#Final table 

cat_gtdk_ID <- merge(gtdbtk_bac120_summary_colon03,gtdbtk_species_colon03, by="classification")

cat_gtdk_ID_col <- cat_gtdk_ID[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species")]
head(cat_gtdk_ID)
nrow(cat_gtdk_ID)

  classification
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
6 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
  user_genome                             closest_genome_reference
1 ERR688569_31866_SZAXPI021631-20_bin.56  GCF_000016525.1
2 ERR688569_31866_SZAXPI021631-20_bin.56  GCF_000016525.1
3 ERR688569_31866_SZAXPI021631-20_bin.56  GCF_000016525.1
4 ERR688569_31866_SZAXPI021631-20_bin.56  GCF_000016525.1
5 ERR688604_530185_SZAXPI021722-32_bin.64 GCF_000016525.1
6 ERR688604_530185_SZAXPI021722-32_bin.64 GCF_000016525.1
  closest_genome_reference_radius
1 95.0
2 95.0
3 95.0
4 95.0
5 95.0
6 95.0
  closest_genome_taxonomy
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
6 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.01              0.884             N/A
2 98.01              0.884             N/A
3 98.01              0.884             N/A
4 98.01              0.884             N/A
5 98.62              0.917             N/A
6 98.62              0.917             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
6 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
6 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.97, 0.811; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.4, 0.406; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.37, 0.445
2 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.97, 0.811; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.4, 0.406; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.37, 0.445
3 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.97, 0.811; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.4, 0.406; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.37, 0.445
4 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.97, 0.811; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.4, 0.406; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.37, 0.445
5 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.57, 0.835; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.87, 0.476; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.56, 0.514
6 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.57, 0.835; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.87, 0.476; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.56, 0.514
  msa_percent translation_table red_value warnings ID
1 N/A         N/A               N/A       N/A      ERR688569
2 N/A         N/A               N/A       N/A      ERR688569
3 N/A         N/A               N/A       N/A      ERR688569
4 N/A         N/A               N/A       N/A      ERR688569
5 N/A         N/A               N/A       N/A      ERR688604
6 N/A         N/A               N/A       N/A      ERR688604
  species
1 Methanocatella smithii
2 Methanocatella smithii
3 Methanocatella smithii
4 Methanocatella smithii
5 Methanocatella smithii
6 Methanocatella smithii

[1] 11557

In [14]:
cat_gtdk_ID_unique <- cat_gtdk_ID%>% distinct(user_genome,.keep_all=TRUE)
nrow(cat_gtdk_ID_unique)
head(cat_gtdk_ID_unique)

[1] 283

  classification
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii_A
6 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii_A
  user_genome                             closest_genome_reference
1 ERR688569_31866_SZAXPI021631-20_bin.56  GCF_000016525.1
2 ERR688604_530185_SZAXPI021722-32_bin.64 GCF_000016525.1
3 ERR688627_530623_SZAXPI021951-21_bin.37 GCF_000016525.1
4 ERR688570_31868_SZAXPI021666-33_bin.12  GCF_000016525.1
5 ERR688506_31009_SZAXPI022053-133_bin.57 GCF_023617305.1
6 ERR688524_31275_SZAXPI021941-129_bin.37 GCF_023617305.1
  closest_genome_reference_radius
1 95.0
2 95.0
3 95.0
4 95.0
5 95.0
6 95.0
  closest_genome_taxonomy
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii_A
6 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii_A
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.01              0.884             N/A
2 98.62              0.917             N/A
3 98.61              0.913             N/A
4 98.43              0.876             N/A
5 98.59              0.93              N/A
6 98.59              0.855             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
6 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
6 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.97, 0.811; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.4, 0.406; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.37, 0.445
2 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.57, 0.835; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.87, 0.476; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.56, 0.514
3 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 87.4, 0.475; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.33, 0.517; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.66, 0.843
4 GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.5, 0.761; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 89.3, 0.39; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 89.95, 0.429
5 GCF_000016525.1, s__Methanocatella smithii, 95.0, 93.32, 0.818; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 88.47, 0.524; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 89.31, 0.526
6 GCF_000016525.1, s__Methanocatella smithii, 95.0, 93.76, 0.742; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 89.66, 0.449; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 88.65, 0.432
  msa_percent translation_table red_value warnings ID
1 N/A         N/A               N/A       N/A      ERR688569
2 N/A         N/A               N/A       N/A      ERR688604
3 N/A         N/A               N/A       N/A      ERR688627
4 N/A         N/A               N/A       N/A      ERR688570
5 N/A         N/A               N/A       N/A      ERR688506
6 N/A         N/A               N/A       N/A      ERR688524
  species
1 Methanocatella smithii
2 Methanocatella smithii
3 Methanocatella smithii
4 Methanocatella smithii
5 Methanocatella smithii_A
6 Methanocatella smithii_A

In [15]:
cat_gtdk_ID_col <- cat_gtdk_ID_unique[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species", "user_genome")]


cat_colon03_preview <- merge(cat_gtdk_ID_col,count_gtdb_colon03, by= "species")
head(cat_colon03_preview)

  species
1 Acetatifactor acetigignens
2 Acutalibacter ornithocaccae
3 Acutalibacter ornithocaccae
4 Acutalibacter ornithocaccae
5 Acutalibacter stercoravium
6 Adlercreutzia rubneri
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Acetatifactor;s__Acetatifactor acetigignens
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Acutalibacter;s__Acutalibacter ornithocaccae
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Acutalibacter;s__Acutalibacter ornithocaccae
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Acutalibacter;s__Acutalibacter ornithocaccae
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Acutalibacteraceae;g__Acutalibacter;s__Acutalibacter stercoravium
6 d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Eggerthellaceae;g__Adlercreutzia;s__Adlercreutzia rubneri
  closest_genome_reference closest_genome_ani ID
1 GCF_025567015.1          98.75              ERR688589
2 GCA_019118965.1          97.86              ERR688527
3 GCA_019118965.1          97.83              ERR688623
4 GCA_019118965.1          97.27              ERR688631
5 GCA_019113615.1          97.95              ERR688606
6 GCF_009755265.1          95.74              ERR688568
  user_genome                             occurrences
1 ERR688589_530041_SZAXPI021954-25_bin.52 1
2 ERR688527_31285_SZAXPI021656-133_bin.77 3
3 ERR688623_530450_SZAXPI021950-20_bin.8  3
4 ERR688631_530756_SZAXPI022085-39_bin.27 3
5 ERR688606_530227_SZAXPI022045-94_bin.18 1
6 ERR688568_31865_SZAXPI021667-39_bin.13  1

In [17]:
# handling with control and disease column

match_colon03_control$State <- "Control"
match_colon03_case$State <- "Disease"

# Change column name

colnames(match_colon03_control)[colnames(match_colon03_control) == "Run"] <- "ID"
colnames(match_colon03_case)[colnames(match_colon03_case) == "Run"] <- "ID"

In [18]:
all_state <- rbind(match_colon03_control,match_colon03_case)

cat_colon03_final <- merge(cat_colon03_preview,all_state, by= "ID")
head(cat_colon03_final)
nrow(cat_colon03_final)

  ID        species
1 ERR688505 Gemmiger formicilis
2 ERR688505 Gemmiger formicilis
3 ERR688505 Gemmiger formicilis
4 ERR688505 Gemmiger sp900539695
5 ERR688505 Gemmiger sp900539695
6 ERR688505 Gemmiger sp900539695
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
  closest_genome_reference closest_genome_ani
1 GCF_900167555.1          98.07
2 GCF_900167555.1          98.07
3 GCF_900167555.1          98.07
4 GCA_025758045.1          98.68
5 GCA_025758045.1          98.68
6 GCA_025758045.1          98.68
  user_genome                             occurrences State
1 ERR688505_31004_SZAXPI021650-108_bin.37 61          Disease
2 ERR688505_31004_SZAXPI021650-108_bin.37 61          Disease
3 ERR688505_31004_SZAXPI021650-108_bin.37 61          Disease
4 ERR688505_31004_SZAXPI021650-108_bin.2  20          Disease
5 ERR688505_31004_SZAXPI021650-108_bin.2  20          Disease
6 ERR688505_31004_SZAXPI021650-108_bin.2  20          Disease

[1] 801

In [19]:
cat_colon03_final_end <- cat_colon03_final %>% distinct(user_genome, .keep_all = TRUE)
nrow(cat_colon03_final_end)

[1] 283

In [ ]:
write_tsv(cat_colon03_final_end, "GTDB_results/final_table_gtdb_for_paper_colon03.tsv")
write_tsv(count_gtdb_colon03, "GTDB_results/species_occurrence.tsv")

In [20]:
# Classify species
classification <- cat_colon03_final_end %>%
  filter(!is.na(species), !is.na(State)) %>%
  group_by(species) %>%
  summarise(
    Group_classification = case_when(
      n_distinct(State) == 1 & first(State) == "Disease" ~ "Disease",
      n_distinct(State) == 1 & first(State) == "Control" ~ "Control",
      n_distinct(State) > 1 ~ "Control/Disease"
    ),
    .groups = "drop"
  )

# Join  and apply rule for Species == NA
cat_colon03_final_end_df <- cat_colon03_final_end %>%
  left_join(classification, by = "species") %>%
  mutate(
    Group_classification = ifelse(
      is.na(species),
      State,
      Group_classification
    )
  )

head(cat_colon03_final_end_df)

  ID        species
1 ERR688505 Gemmiger formicilis
2 ERR688505 Gemmiger sp900539695
3 ERR688505 Gemmiger qucibialis
4 ERR688506 Methanocatella smithii_A
5 ERR688506 Fusicatenibacter saccharivorans
6 ERR688506 Bacteroides_F pectinophilus
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger qucibialis
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii_A
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Fusicatenibacter;s__Fusicatenibacter saccharivorans
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Bacteroides_F;s__Bacteroides_F pectinophilus
  closest_genome_reference closest_genome_ani
1 GCF_900167555.1          98.07
2 GCA_025758045.1          98.68
3 GCA_004000625.1          98.61
4 GCF_023617305.1          98.59
5 GCF_027667425.1          97.42
6 GCA_025146925.1          98.8
  user_genome                             occurrences State
1 ERR688505_31004_SZAXPI021650-108_bin.37 61          Disease
2 ERR688505_31004_SZAXPI021650-108_bin.2  20          Disease
3 ERR688505_31004_SZAXPI021650-108_bin.3  80          Disease
4 ERR688506_31009_SZAXPI022053-133_bin.57 13          Control
5 ERR688506_31009_SZAXPI022053-133_bin.27  3          Control
6 ERR688506_31009_SZAXPI022053-133_bin.50  1          Control
  Group_classification
1 Control/Disease
2 Control/Disease
3 Control/Disease
4 Control/Disease
5 Control/Disease
6 Control

In [ ]:
write_tsv(cat_colon03_final_end_df,"GTDB_results/gtdb_final_table_with_condition_colon03_corrected.tsv")

In [21]:
cat_colon03_final_end_df_col <- cat_colon03_final_end_df[ ,c("species", "occurrences", "Group_classification")]

cat_colon03_final_end_df_col_unique <- cat_colon03_final_end_df_col %>% distinct(species, .keep_all = TRUE)

head(cat_colon03_final_end_df_col_unique)
nrow(cat_colon03_final_end_df_col_unique)

  species                         occurrences Group_classification
1 Gemmiger formicilis             61          Control/Disease
2 Gemmiger sp900539695            20          Control/Disease
3 Gemmiger qucibialis             80          Control/Disease
4 Methanocatella smithii_A        13          Control/Disease
5 Fusicatenibacter saccharivorans  3          Control/Disease
6 Bacteroides_F pectinophilus      1          Control

[1] 45

In [ ]:
write_tsv(cat_colon03_final_end_df_col_unique, "GTDB_results/count_ocurrence_w_condition_for_paper_colon03.tsv")