In [2]:
#Libraries
library(readr)
library(data.table)
library(dplyr)
library(stringr)

In [4]:
setwd("/mnt/l/atero1_hmmer_backup/")

In [5]:
matched_CMP_ID_interpro_atero01 <- read_delim("Interpro_results/atero01_CMP_ID_sequence_for_Interpro.tsv_retrieved_now_results.tsv", 
                                              delim = "\t", escape_double = FALSE, 
                                              col_names = FALSE, trim_ws = TRUE)


column_names_interpro <-c("Sequence", "md5", "unkown", "Bank", "signature", "annotation", "align_begin",
                          "align_end", "e-value","Hit", "date", "Interpro_code", "annotation_two", "unkown2", "unkown3")

setnames(matched_CMP_ID_interpro_atero01, column_names_interpro)

unique(matched_CMP_ID_interpro_atero01$annotation)

patterns_of_teste_CMP <- c("TIGR00466","PTHR42866","NF003952", "cd02517", "MF_00057", "TIGR03584") #remove only other nonulosonic citidyltransferase

Rows: 6403 Columns: 15
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): X1, X2, X4, X5, X6, X9, X11, X12, X13, X14, X15
dbl  (3): X3, X7, X8
lgl  (1): X10

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

 [1] "Nucleotide-diphospho-sugar transferases"
 [2] "Spore Coat Polysaccharide Biosynthesis Protein SpsA; Chain A"
 [3] "HAD SUPERFAMILY MEMBERS CMAS AND KDSC"
 [4] "3-deoxy-manno-octulosonate cytidylyltransferase"
 [5] "Cytidylyltransferase"
 [6] "CMP-KDO-Synthetase"
 [7] "3-DEOXY-MANNO-OCTULOSONATE CYTIDYLYLTRANSFERASE"
 [8] "CMP-NeuAc_Synthase"
 [9] "Glycogen Phosphorylase B;"
[10] "UDP-Glycosyltransferase/glycogen phosphorylase"
[11] "-"
[12] "SGNH hydrolase"
[13] "Coil"
[14] "GDSL-like Lipase/Acylhydrolase family"
[15] "pseudaminic acid cytidylyltransferase"
[16] "Glyceraldehyde-3-phosphate dehydrogenase-like, C-terminal domain"
[17] "NAD(P)-binding Rossmann-fold domains"
[18] "Dihydrodipicolinate Reductase; domain 2"
[19] "Oxidoreductase family, NAD-binding Rossmann fold"
[20] "3-deoxy-D-manno-octulosonate 8-phosphate phosphatase, YrbI family"
[21] "HAD_KDO-like"
[22] "Haloacid Dehalogenase"
[23] "haloacid dehalogenase-like hydrolase"
[24] "HAD-like"
[25] "C1.6: Phosphoserine Phosphatase Like"
[26] "C1.6.2: Deoxy-d-mannose-octulosonate 8-phosphate Phosphatase Like"
[27] "Glycosyltransferase family 28 C-terminal domain"
[28] "HAD-IIIA family hydrolase"
[29] "NnaC_like"
[30] "Haloacid dehalogenase-like hydrolase"
[31] "GT2_SpsF"

In [6]:
# 1. Find all Sequence IDs containing any of the patterns
bad_ids <- matched_CMP_ID_interpro_atero01 %>%
  filter(grepl(paste(patterns_of_teste_CMP, collapse = "|"), signature)) %>%
  pull(Sequence) %>%
  unique()

# 2. Remove those IDs entirely
filtered_CMP_interpro_rm_atero01 <- matched_CMP_ID_interpro_atero01 %>%
  filter(!(Sequence %in% bad_ids))

patterns <- c("PF02348","SSF53448","G3DSA:3.90.550.10","PTHR21485","cd02513")

filtered_CMP_interpro_atero01 <- filtered_CMP_interpro_rm_atero01 %>%
  filter(signature %in% patterns)

head(filtered_CMP_interpro_atero01)
CMP_interpro_distinct_atero01 <- filtered_CMP_interpro_atero01%>% distinct(Sequence, .keep_all = TRUE)

  Sequence
1 PROKKA_ERR2017550_N194_bin.37.faa_LEOCINGE_00349
2 PROKKA_ERR2017550_N194_bin.37.faa_LEOCINGE_00349
3 PROKKA_ERR2017550_N194_bin.37.faa_LEOCINGE_00349
4 PROKKA_ERR2017804_ZSL524_bin.30.faa_EBIOCABM_00195
5 PROKKA_ERR2017804_ZSL524_bin.30.faa_EBIOCABM_00195
6 PROKKA_ERR2017804_ZSL524_bin.30.faa_EBIOCABM_00195
  md5                              unkown Bank        signature
1 d4baab9a66e550a027d6174a65cfcf19 231    SUPERFAMILY SSF53448
2 d4baab9a66e550a027d6174a65cfcf19 231    Gene3D      G3DSA:3.90.550.10
3 d4baab9a66e550a027d6174a65cfcf19 231    PANTHER     PTHR21485
4 89be0caa7a9232917ffae142eaffc415 222    PANTHER     PTHR21485
5 89be0caa7a9232917ffae142eaffc415 222    Pfam        PF02348
6 89be0caa7a9232917ffae142eaffc415 222    Gene3D      G3DSA:3.90.550.10
  annotation                                                   align_begin
1 Nucleotide-diphospho-sugar transferases                      7
2 Spore Coat Polysaccharide Biosynthesis Protein SpsA; Chain A 2
3 HAD SUPERFAMILY MEMBERS CMAS AND KDSC                        4
4 HAD SUPERFAMILY MEMBERS CMAS AND KDSC                        2
5 Cytidylyltransferase                                         4
6 Spore Coat Polysaccharide Biosynthesis Protein SpsA; Chain A 1
  align_end e-value  Hit  date       Interpro_code
1 227       1.75E-28 TRUE 02-03-2026 IPR029044
2 226       1.2E-38  TRUE 02-03-2026 IPR029044
3 226       2.4E-22  TRUE 02-03-2026 IPR050793
4 212       6.2E-34  TRUE 02-03-2026 IPR050793
5 207       8.1E-12  TRUE 02-03-2026 IPR003329
6 214       6.7E-49  TRUE 02-03-2026 IPR029044
  annotation_two                          unkown2 unkown3
1 Nucleotide-diphospho-sugar transferases -       -
2 Nucleotide-diphospho-sugar transferases -       -
3 CMP-NeuNAc synthase                     -       -
4 CMP-NeuNAc synthase                     -       -
5 Acylneuraminate cytidylyltransferase    -       -
6 Nucleotide-diphospho-sugar transferases -       -

In [7]:
##############################################################
#pm1088

pm1088_Interpro_data_atero01 <- read_delim("Interpro_results/atero01_pm0188_ID_sequence_for_Interpro.tsv_retrieved_now_results.tsv", 
                                           delim = "\t", escape_double = FALSE, 
                                           col_names = FALSE, trim_ws = TRUE)
head(pm1088_Interpro_data_atero01)

setnames(pm1088_Interpro_data_atero01, column_names_interpro)


pm1088_interpro_annot_unique_atero01 <- unique(pm1088_Interpro_data_atero01$annotation)
pm1088_interpro_annot_unique_atero01

patterns_off_pm1088 <- c("PTHR30160","PF01075","G3DSA:2.60.40.10","cd14948","G3DSA:3.40.50.2000", "PF22352")

Rows: 176 Columns: 15
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (10): X1, X2, X4, X5, X6, X11, X12, X13, X14, X15
dbl  (4): X3, X7, X8, X9
lgl  (1): X10

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  X1
1 PROKKA_ERR2017741_ZSL368_bin.33.faa_FPJJGPEC_01578
2 PROKKA_ERR2017741_ZSL368_bin.33.faa_FPJJGPEC_01578
3 PROKKA_ERR2017741_ZSL368_bin.33.faa_FPJJGPEC_01578
4 PROKKA_ERR2017741_ZSL368_bin.33.faa_FPJJGPEC_01578
5 PROKKA_ERR2017776_ZSL453_bin.10.faa_EMBEELFF_01028
6 PROKKA_ERR2017776_ZSL453_bin.10.faa_EMBEELFF_01028
  X2                               X3  X4          X5
1 c8c2d0d1f47e96ab32575c11250bd4c7 498 SUPERFAMILY SSF53756
2 c8c2d0d1f47e96ab32575c11250bd4c7 498 CDD         cd14948
3 c8c2d0d1f47e96ab32575c11250bd4c7 498 Gene3D      G3DSA:2.60.40.10
4 c8c2d0d1f47e96ab32575c11250bd4c7 498 Gene3D      G3DSA:3.40.50.11110
5 c8c2d0d1f47e96ab32575c11250bd4c7 498 SUPERFAMILY SSF53756
6 c8c2d0d1f47e96ab32575c11250bd4c7 498 CDD         cd14948
  X6                                             X7  X8  X9          X10
1 UDP-Glycosyltransferase/glycogen phosphorylase 236 474 5.65000e-15 TRUE
2 BACON                                           36 115 2.11193e-11 TRUE
3 Immunoglobulins                                 29 109 1.20000e-07 TRUE
4 -                                              358 489 4.50000e-29 TRUE
5 UDP-Glycosyltransferase/glycogen phosphorylase 236 474 5.65000e-15 TRUE
6 BACON                                           36 115 2.11193e-11 TRUE
  X11        X12
1 02-03-2026 -
2 02-03-2026 IPR024361
3 02-03-2026 IPR013783
4 02-03-2026 -
5 02-03-2026 -
6 02-03-2026 IPR024361
  X13                                                            X14 X15
1 -                                                              -   -
2 Bacteroidetes-Associated Carbohydrate-binding Often N-terminal -   -
3 Immunoglobulin-like fold                                       -   -
4 -                                                              -   -
5 -                                                              -   -
6 Bacteroidetes-Associated Carbohydrate-binding Often N-terminal -   -

[1] "UDP-Glycosyltransferase/glycogen phosphorylase"
[2] "BACON"
[3] "Immunoglobulins"
[4] "-"
[5] "Sialyltransferase PMO188"

In [8]:
# 1. Find all Sequence IDs containing any of the patterns
bad_ids_pm1088_atero01 <- pm1088_Interpro_data_atero01 %>%
  filter(grepl(paste(patterns_off_pm1088, collapse = "|"), signature)) %>%
  pull(Sequence) %>%
  unique()

# 2. Remove those IDs entirely
filtered_pm1088_interpro_atero01 <- pm1088_Interpro_data_atero01 %>%
  filter(!(Sequence %in% bad_ids_pm1088_atero01))


patterns_pm1088 <- c("PF11477")

filtered_pm1088_interpro_atero01_test <- filtered_pm1088_interpro_atero01 %>%
  filter(signature %in% patterns_pm1088)

pm1088_interpro_distinct_atero01 <- filtered_pm1088_interpro_atero01_test  %>% distinct(Sequence, .keep_all = TRUE) 

head(pm1088_interpro_distinct_atero01)

  Sequence
1 PROKKA_ERR2017725_ZSL325_bin.19.faa_FBKOIEHO_01732
2 PROKKA_ERR2017575_N227_bin.1.faa_GBNEPCJE_00113
  md5                              unkown Bank signature
1 a9d79d1388c100898903f7f96a9ff1f4 389    Pfam PF11477
2 96ae703ab876d99d2a3250a64a29d108 389    Pfam PF11477
  annotation               align_begin align_end e-value Hit  date
1 Sialyltransferase PMO188 4           362       4.9e-23 TRUE 02-03-2026
2 Sialyltransferase PMO188 4           362       8.9e-23 TRUE 02-03-2026
  Interpro_code annotation_two           unkown2 unkown3
1 IPR021574     Sialyltransferase PMO188 -       -
2 IPR021574     Sialyltransferase PMO188 -       -

In [9]:
#NeuS PFAM


neuS_PFAM_interpro_data_atero01 <- read_delim("Interpro_results/atero01_IPR010866_ID_sequence_for_Interpro.tsv_retrieved_now_results.tsv", 
                                              delim = "\t", escape_double = FALSE, 
                                              col_names = FALSE, trim_ws = TRUE)
head(neuS_PFAM_interpro_data_atero01)

setnames(neuS_PFAM_interpro_data_atero01, column_names_interpro)


neuS_PFAM_interpro_annot_unique_atero01 <- unique(neuS_PFAM_interpro_data_atero01$annotation)


patterns_neuS <- c("PF07388")

filtered_neuS_PFAM_interpro_atero01 <- neuS_PFAM_interpro_data_atero01 %>%
  filter(signature %in% patterns_neuS)

Rows: 980 Columns: 15
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): X1, X2, X4, X5, X6, X9, X11, X12, X13, X14, X15
dbl  (3): X3, X7, X8
lgl  (1): X10

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  X1
1 PROKKA_ERR2017484_N1272_bin.52.faa_HPEMFNPI_02148
2 PROKKA_ERR2017458_N088_bin.6.faa_JODLPINN_01415
3 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
4 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
5 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
6 PROKKA_ERR2017558_N203_bin.73.faa_DPPNDGGA_01874
  X2                               X3  X4     X5
1 1b4fc1026ed1cdb65afd456084ed5cf9 358 Pfam   PF07388
2 1125066e906c39bddb7b5d63132a7a4d 368 Pfam   PF07388
3 9f1440113843be9101ff6b398571c85e 361 Pfam   PF07922
4 9f1440113843be9101ff6b398571c85e 361 Coils  Coil
5 9f1440113843be9101ff6b398571c85e 361 Gene3D G3DSA:3.40.50.11110
6 9f1440113843be9101ff6b398571c85e 361 Pfam   PF07922
  X6                                       X7  X8  X9      X10  X11
1 Alpha-2,8-polysialyltransferase (POLYST) 131 316 0.0014  TRUE 02-03-2026
2 Alpha-2,8-polysialyltransferase (POLYST)   3 300 0.003   TRUE 02-03-2026
3 Glycosyltransferase family 52            115 313 7.9E-10 TRUE 02-03-2026
4 Coil                                     226 246 -       TRUE 02-03-2026
5 -                                        218 329 2.3E-5  TRUE 02-03-2026
6 Glycosyltransferase family 52            115 313 7.9E-10 TRUE 02-03-2026
  X12       X13                             X14 X15
1 IPR010866 Alpha-2,8-polysialyltransferase -   -
2 IPR010866 Alpha-2,8-polysialyltransferase -   -
3 IPR012477 Glycosyltransferase family 52   -   -
4 -         -                               -   -
5 -         -                               -   -
6 IPR012477 Glycosyltransferase family 52   -   -

In [11]:
neuS_PFAM_interpro_distinct_atero01 <- filtered_neuS_PFAM_interpro_atero01 %>% distinct(Sequence, .keep_all = TRUE)

head(neuS_PFAM_interpro_distinct_atero01)
nrow(neuS_PFAM_interpro_distinct_atero01)

  Sequence
1 PROKKA_ERR2017484_N1272_bin.52.faa_HPEMFNPI_02148
2 PROKKA_ERR2017458_N088_bin.6.faa_JODLPINN_01415
3 PROKKA_ERR2017699_ZSL277_bin.8.faa_JLGPDBIA_00317
4 PROKKA_ERR2017474_N1262_bin.18.faa_LBOHIJID_01134
5 PROKKA_ERR2017814_ZSL_82_bin.19.faa_CNLAAJGA_01528
6 PROKKA_ERR2017713_ZSL306_bin.1.faa_DCHCMJJN_00903
  md5                              unkown Bank signature
1 1b4fc1026ed1cdb65afd456084ed5cf9 358    Pfam PF07388
2 1125066e906c39bddb7b5d63132a7a4d 368    Pfam PF07388
3 541579c2ab935b91ec3bfca7cb84e4b4 425    Pfam PF07388
4 eb049c449e0c15217e3c2183467d6fdc 360    Pfam PF07388
5 669a49ee348235d809116c54b62738dd 349    Pfam PF07388
6 669a49ee348235d809116c54b62738dd 349    Pfam PF07388
  annotation                               align_begin align_end e-value Hit
1 Alpha-2,8-polysialyltransferase (POLYST) 131         316       0.0014  TRUE
2 Alpha-2,8-polysialyltransferase (POLYST)   3         300       0.003   TRUE
3 Alpha-2,8-polysialyltransferase (POLYST) 148         360       0.044   TRUE
4 Alpha-2,8-polysialyltransferase (POLYST)   3         317       1.3E-12 TRUE
5 Alpha-2,8-polysialyltransferase (POLYST)   3         317       3.9E-9  TRUE
6 Alpha-2,8-polysialyltransferase (POLYST)   3         317       3.9E-9  TRUE
  date       Interpro_code annotation_two                  unkown2 unkown3
1 02-03-2026 IPR010866     Alpha-2,8-polysialyltransferase -       -
2 02-03-2026 IPR010866     Alpha-2,8-polysialyltransferase -       -
3 02-03-2026 IPR010866     Alpha-2,8-polysialyltransferase -       -
4 02-03-2026 IPR010866     Alpha-2,8-polysialyltransferase -       -
5 02-03-2026 IPR010866     Alpha-2,8-polysialyltransferase -       -
6 02-03-2026 IPR010866     Alpha-2,8-polysialyltransferase -       -

[1] 214

In [12]:
#

###############################################################################################################
#NeuS

neuS_interpro_data_atero01 <- read_delim("Interpro_results/atero01_neuS_ID_sequence_for_Interpro.tsv_retrieved_now_results.tsv", 
                                         delim = "\t", escape_double = FALSE, 
                                         col_names = FALSE, trim_ws = TRUE)
head(neuS_interpro_data_atero01)

setnames(neuS_interpro_data_atero01, column_names_interpro)


neuS_interpro_annot_unique_atero01 <- unique(neuS_interpro_data_atero01$annotation)


patterns_neuS <- c("PF07388")

filtered_neuS_interpro_atero01 <- neuS_interpro_data_atero01 %>%
  filter(signature %in% patterns_neuS)



neuS_interpro_distinct_atero01 <- filtered_neuS_interpro_atero01 %>% distinct(Sequence, .keep_all = TRUE)

Rows: 1581 Columns: 15
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): X1, X2, X4, X5, X6, X9, X11, X12, X13, X14, X15
dbl  (3): X3, X7, X8
lgl  (1): X10

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  X1
1 PROKKA_ERR2017484_N1272_bin.52.faa_HPEMFNPI_02148
2 PROKKA_ERR2017634_ZSL-079_bin.39.faa_BKDIIPAJ_01387
3 PROKKA_ERR2017557_N202_bin.34.faa_NDNFIFAH_00131
4 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
5 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
6 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
  X2                               X3  X4     X5
1 1b4fc1026ed1cdb65afd456084ed5cf9 358 Pfam   PF07388
2 686957ebae566428a4f37e9fcd49b505 322 Pfam   PF07922
3 686957ebae566428a4f37e9fcd49b505 322 Pfam   PF07922
4 9f1440113843be9101ff6b398571c85e 361 Pfam   PF07922
5 9f1440113843be9101ff6b398571c85e 361 Coils  Coil
6 9f1440113843be9101ff6b398571c85e 361 Gene3D G3DSA:3.40.50.11110
  X6                                       X7  X8  X9      X10  X11
1 Alpha-2,8-polysialyltransferase (POLYST) 131 316 0.0014  TRUE 02-03-2026
2 Glycosyltransferase family 52            199 284 7.5E-5  TRUE 02-03-2026
3 Glycosyltransferase family 52            199 284 7.5E-5  TRUE 02-03-2026
4 Glycosyltransferase family 52            115 313 7.9E-10 TRUE 02-03-2026
5 Coil                                     226 246 -       TRUE 02-03-2026
6 -                                        218 329 2.3E-5  TRUE 02-03-2026
  X12       X13                             X14 X15
1 IPR010866 Alpha-2,8-polysialyltransferase -   -
2 IPR012477 Glycosyltransferase family 52   -   -
3 IPR012477 Glycosyltransferase family 52   -   -
4 IPR012477 Glycosyltransferase family 52   -   -
5 -         -                               -   -
6 -         -                               -   -

In [13]:
########################################################################################################################
#Lst

Lst_Interpro_data_atero01 <- read_delim("Interpro_results/atero01_lst_ID_sequence_for_Interpro.tsv_retrieved_now_results.tsv", 
                                        delim = "\t", escape_double = FALSE, 
                                        col_names = FALSE, trim_ws = TRUE)
head(Lst_Interpro_data_atero01)

setnames(Lst_Interpro_data_atero01, column_names_interpro)

lst_interpro_annot_unique_atero01 <- unique(Lst_Interpro_data_atero01$annotation)



patterns_Lst <- c("PF07922")

filtered_Lst_interpro_atero01 <- Lst_Interpro_data_atero01 %>%
  filter(signature %in% patterns_Lst)

head(filtered_Lst_interpro_atero01)
lst_filtered_annot_unique_atero01 <- unique(filtered_Lst_interpro_atero01$annotation)

Lst_interpro_distinct_atero01 <- filtered_Lst_interpro_atero01 %>% distinct(Sequence, .keep_all = TRUE)

Rows: 740 Columns: 15
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): X1, X2, X4, X5, X6, X9, X11, X12, X13, X14, X15
dbl  (3): X3, X7, X8
lgl  (1): X10

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  X1
1 PROKKA_ERR2017634_ZSL-079_bin.39.faa_BKDIIPAJ_01387
2 PROKKA_ERR2017557_N202_bin.34.faa_NDNFIFAH_00131
3 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
4 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
5 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
6 PROKKA_ERR2017558_N203_bin.73.faa_DPPNDGGA_01874
  X2                               X3  X4     X5
1 686957ebae566428a4f37e9fcd49b505 322 Pfam   PF07922
2 686957ebae566428a4f37e9fcd49b505 322 Pfam   PF07922
3 9f1440113843be9101ff6b398571c85e 361 Pfam   PF07922
4 9f1440113843be9101ff6b398571c85e 361 Coils  Coil
5 9f1440113843be9101ff6b398571c85e 361 Gene3D G3DSA:3.40.50.11110
6 9f1440113843be9101ff6b398571c85e 361 Pfam   PF07922
  X6                            X7  X8  X9      X10  X11        X12
1 Glycosyltransferase family 52 199 284 7.5E-5  TRUE 02-03-2026 IPR012477
2 Glycosyltransferase family 52 199 284 7.5E-5  TRUE 02-03-2026 IPR012477
3 Glycosyltransferase family 52 115 313 7.9E-10 TRUE 02-03-2026 IPR012477
4 Coil                          226 246 -       TRUE 02-03-2026 -
5 -                             218 329 2.3E-5  TRUE 02-03-2026 -
6 Glycosyltransferase family 52 115 313 7.9E-10 TRUE 02-03-2026 IPR012477
  X13                           X14 X15
1 Glycosyltransferase family 52 -   -
2 Glycosyltransferase family 52 -   -
3 Glycosyltransferase family 52 -   -
4 -                             -   -
5 -                             -   -
6 Glycosyltransferase family 52 -   -

  Sequence
1 PROKKA_ERR2017634_ZSL-079_bin.39.faa_BKDIIPAJ_01387
2 PROKKA_ERR2017557_N202_bin.34.faa_NDNFIFAH_00131
3 PROKKA_ERR2017534_N171_bin.27.faa_NANCEPEJ_01208
4 PROKKA_ERR2017558_N203_bin.73.faa_DPPNDGGA_01874
5 PROKKA_ERR2017580_N235_bin.48.faa_KDAHDIHH_01359
6 PROKKA_ERR2017563_N210_bin.14.faa_LHCCPKGI_01090
  md5                              unkown Bank signature
1 686957ebae566428a4f37e9fcd49b505 322    Pfam PF07922
2 686957ebae566428a4f37e9fcd49b505 322    Pfam PF07922
3 9f1440113843be9101ff6b398571c85e 361    Pfam PF07922
4 9f1440113843be9101ff6b398571c85e 361    Pfam PF07922
5 9f1440113843be9101ff6b398571c85e 361    Pfam PF07922
6 9f1440113843be9101ff6b398571c85e 361    Pfam PF07922
  annotation                    align_begin align_end e-value Hit  date
1 Glycosyltransferase family 52 199         284       7.5E-5  TRUE 02-03-2026
2 Glycosyltransferase family 52 199         284       7.5E-5  TRUE 02-03-2026
3 Glycosyltransferase family 52 115         313       7.9E-10 TRUE 02-03-2026
4 Glycosyltransferase family 52 115         313       7.9E-10 TRUE 02-03-2026
5 Glycosyltransferase family 52 115         313       7.9E-10 TRUE 02-03-2026
6 Glycosyltransferase family 52 115         313       7.9E-10 TRUE 02-03-2026
  Interpro_code annotation_two                unkown2 unkown3
1 IPR012477     Glycosyltransferase family 52 -       -
2 IPR012477     Glycosyltransferase family 52 -       -
3 IPR012477     Glycosyltransferase family 52 -       -
4 IPR012477     Glycosyltransferase family 52 -       -
5 IPR012477     Glycosyltransferase family 52 -       -
6 IPR012477     Glycosyltransferase family 52 -       -

In [16]:
#pm0188 PFAM - PF11477


pm1088_PFAM_Interpro_atero01 <- read_delim("Interpro_results/atero01_PF11477_ID_sequence_for_Interpro.tsv_retrieved_now_results.tsv", 
                                           delim = "\t", escape_double = FALSE, 
                                           col_names = FALSE, trim_ws = TRUE)

setnames(pm1088_PFAM_Interpro_atero01, column_names_interpro)

pm1088_PFAM_interpro_annot_unique_atero01 <- unique(pm1088_PFAM_Interpro_atero01$annotation)
pm1088_PFAM_interpro_annot_unique_atero01

head(pm1088_PFAM_Interpro_atero01)
nrow(pm1088_PFAM_Interpro_atero01)

patterns_off_pm1088 <- c("PTHR30160","PF01075","G3DSA:2.60.40.10","cd14948","G3DSA:3.40.50.2000", "PF22352")

Rows: 8 Columns: 15
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (10): X1, X2, X4, X5, X6, X11, X12, X13, X14, X15
dbl  (4): X3, X7, X8, X9
lgl  (1): X10

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] "-"
[2] "Sialyltransferase PMO188"
[3] "UDP-Glycosyltransferase/glycogen phosphorylase"

  Sequence
1 PROKKA_ERR2017725_ZSL325_bin.19.faa_FBKOIEHO_01732
2 PROKKA_ERR2017725_ZSL325_bin.19.faa_FBKOIEHO_01732
3 PROKKA_ERR2017725_ZSL325_bin.19.faa_FBKOIEHO_01732
4 PROKKA_ERR2017725_ZSL325_bin.19.faa_FBKOIEHO_01732
5 PROKKA_ERR2017575_N227_bin.1.faa_GBNEPCJE_00113
6 PROKKA_ERR2017575_N227_bin.1.faa_GBNEPCJE_00113
  md5                              unkown Bank        signature
1 a9d79d1388c100898903f7f96a9ff1f4 389    Gene3D      G3DSA:3.40.50.11120
2 a9d79d1388c100898903f7f96a9ff1f4 389    Pfam        PF11477
3 a9d79d1388c100898903f7f96a9ff1f4 389    SUPERFAMILY SSF53756
4 a9d79d1388c100898903f7f96a9ff1f4 389    Gene3D      G3DSA:3.40.50.11110
5 96ae703ab876d99d2a3250a64a29d108 389    SUPERFAMILY SSF53756
6 96ae703ab876d99d2a3250a64a29d108 389    Gene3D      G3DSA:3.40.50.11120
  annotation                                     align_begin align_end e-value
1 -                                                2         229       2.70e-56
2 Sialyltransferase PMO188                         4         362       4.90e-23
3 UDP-Glycosyltransferase/glycogen phosphorylase   4         385       6.28e-34
4 -                                              232         389       3.10e-31
5 UDP-Glycosyltransferase/glycogen phosphorylase   4         385       3.14e-33
6 -                                                2         229       5.00e-56
  Hit  date       Interpro_code
1 TRUE 02-03-2026 IPR043078
2 TRUE 02-03-2026 IPR021574
3 TRUE 02-03-2026 -
4 TRUE 02-03-2026 -
5 TRUE 02-03-2026 -
6 TRUE 02-03-2026 IPR043078
  annotation_two                                                       unkown2
1 Sialyltransferase, N-terminal GT-B Rossman nucleotide-binding domain -
2 Sialyltransferase PMO188                                             -
3 -                                                                    -
4 -                                                                    -
5 -                                                                    -
6 Sialyltransferase, N-terminal GT-B Rossman nucleotide-binding domain -
  unkown3
1 -
2 -
3 -
4 -
5 -
6 -

[1] 8

In [17]:
# 1. Find all Sequence IDs containing any of the patterns
bad_ids_pm1088_PFAM_UHGP <- pm1088_PFAM_Interpro_atero01 %>%
  filter(grepl(paste(patterns_off_pm1088, collapse = "|"), signature)) %>%
  pull(Sequence) %>%
  unique()

# 2. Remove those IDs entirely
filtered_pm1088_PFAM_interpro_atero01 <- pm1088_PFAM_Interpro_atero01 %>%
  filter(!(Sequence %in% bad_ids_pm1088_PFAM_UHGP))

real_pm1088_PFAM_interpro_distinct_atero01 <- filtered_pm1088_PFAM_interpro_atero01 %>% distinct(Sequence, .keep_all = TRUE)

head(real_pm1088_PFAM_interpro_distinct_atero01)
nrow(real_pm1088_PFAM_interpro_distinct_atero01)

  Sequence
1 PROKKA_ERR2017725_ZSL325_bin.19.faa_FBKOIEHO_01732
2 PROKKA_ERR2017575_N227_bin.1.faa_GBNEPCJE_00113
  md5                              unkown Bank        signature
1 a9d79d1388c100898903f7f96a9ff1f4 389    Gene3D      G3DSA:3.40.50.11120
2 96ae703ab876d99d2a3250a64a29d108 389    SUPERFAMILY SSF53756
  annotation                                     align_begin align_end e-value
1 -                                              2           229       2.70e-56
2 UDP-Glycosyltransferase/glycogen phosphorylase 4           385       3.14e-33
  Hit  date       Interpro_code
1 TRUE 02-03-2026 IPR043078
2 TRUE 02-03-2026 -
  annotation_two                                                       unkown2
1 Sialyltransferase, N-terminal GT-B Rossman nucleotide-binding domain -
2 -                                                                    -
  unkown3
1 -
2 -

[1] 2

In [19]:
patterns_pm1088 <- c("PF11477")

filtered_pm1088_PFAM_interpro_test_atero01 <- filtered_pm1088_PFAM_interpro_atero01 %>%
  filter(signature %in% patterns_pm1088)

pm1088_PFAM_interpro_distinct_atero01 <- filtered_pm1088_PFAM_interpro_test_atero01  %>% distinct(Sequence, .keep_all = TRUE)
nrow(pm1088_PFAM_interpro_distinct_atero01)

[1] 2

In [20]:
##################################################################################################
#join all data


#extract GCF ID
CMP_interpro_distinct_atero01$GCF_ID <- str_extract(CMP_interpro_distinct_atero01$Sequence,
                                                    ".*?\\.faa")

#get CMP GCF ID
get_CMP_final_interpro_ID_atero01 <- CMP_interpro_distinct_atero01[,"GCF_ID"]


#pm1088
pm1088_interpro_distinct_atero01$GCF_ID <- str_extract(pm1088_interpro_distinct_atero01$Sequence,
                                                       ".*?\\.faa")
get_pm1088_final_interpro_ID_atero01 <- pm1088_interpro_distinct_atero01[,"GCF_ID"]


#NeuS
neuS_interpro_distinct_atero01$GCF_ID <- str_extract(neuS_interpro_distinct_atero01$Sequence,
                                                     ".*?\\.faa")
get_neuS_final_interpro_ID_atero01 <- neuS_interpro_distinct_atero01[,"GCF_ID"]

#NeuS PFAM
neuS_PFAM_interpro_distinct_atero01$GCF_ID <- str_extract(neuS_PFAM_interpro_distinct_atero01$Sequence,
                                                          ".*?\\.faa")
get_neuS_PFAM_final_interpro_ID_atero01 <- neuS_PFAM_interpro_distinct_atero01[,"GCF_ID"]

#Lst 
Lst_interpro_distinct_atero01$GCF_ID <- str_extract(Lst_interpro_distinct_atero01$Sequence,
                                                    ".*?\\.faa")
get_Lst_final_interpro_ID_atero01 <- Lst_interpro_distinct_atero01[,"GCF_ID"]

#pm1088 - PFAM
pm1088_PFAM_interpro_distinct_atero01$GCF_ID <- str_extract(pm1088_PFAM_interpro_distinct_atero01$Sequence,
                                                            ".*?\\.faa")
get_pm1088_PFAM_final_interpro_ID_atero01 <- pm1088_PFAM_interpro_distinct_atero01[,"GCF_ID"]

In [21]:
#join all sialyltransferase
all_sialyltrans_ID_atero01 <- rbind(get_neuS_final_interpro_ID_atero01,get_Lst_final_interpro_ID_atero01,
                                    get_neuS_PFAM_final_interpro_ID_atero01,get_pm1088_PFAM_final_interpro_ID_atero01,
                                    get_pm1088_final_interpro_ID_atero01)

all_sialyltrans_ID_unique_atero01 <-all_sialyltrans_ID_atero01 %>% distinct(GCF_ID)

In [22]:
#After filtration, see what are complete pathway that match with CMP
complete_sialylation_interpro_atero01 <- semi_join(get_CMP_final_interpro_ID_atero01, all_sialyltrans_ID_unique_atero01, by="GCF_ID")

write_tsv(complete_sialylation_interpro_atero01, 
          "Interpro_results/complete_sialylation_interpro_filtration_final_atero01_metagen_update.tsv")

#get bins
get_bins_atero01 <- semi_join(CMP_interpro_distinct_atero01, complete_sialylation_interpro_atero01, by="GCF_ID")
get_bins_atero01_ID <- get_bins_atero01[,"Sequence"]


get_bins_atero01_ID <- get_bins_atero01_ID %>%
  mutate(Sequence = Sequence %>%
           str_remove("^PROKKA_") %>%
           str_replace("\\.faa.*$", ".fa"))

In [ ]:
write_tsv(get_bins_atero01_ID, "get_bins_file_atero01.tsv")