In [1]:
# Upload libraries
library(readr)
library(dplyr)
library(stringr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
setwd("/mnt/l/atero1_hmmer_backup")

In [3]:
#get unique species

all_gtdbtk_bac120_summary_atero01 <- read_delim("all_atero01_summ_gtdb_arch_bac.tsv", 
                                                delim = "\t", escape_double = FALSE, 
                                                trim_ws = TRUE)
head(all_gtdbtk_bac120_summary_atero01)

Rows: 336 Columns: 20
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (20): user_genome, classification, closest_genome_reference, closest_gen...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR2017413_N003_bin.17
2 ERR2017414_N005_bin.2
3 ERR2017420_N020_bin.28
4 ERR2017421_N021_bin.11
5 ERR2017422_N022_bin.34
6 ERR2017423_N024_bin.10
  classification
1 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
2 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
3 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides salyersiae
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides intestinalis
5 Unclassified Bacteria
6 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
  closest_genome_reference closest_genome_reference_radius
1 GCF_000158195.2          95.0
2 GCF_000158195.2          95.0
3 GCF_000381365.1          95.0
4 GCF_000172175.1          95.0
5 N/A                      N/A
6 GCF_000158195.2          95.0
  closest_genome_taxonomy
1 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
2 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
3 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides salyersiae
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides intestinalis
5 N/A
6 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
  closest_genome_ani closest_genome_af closest_placement_reference
1 99.13              0.875             N/A
2 98.78              0.874             N/A
3 99.29              0.648             N/A
4 98.24              0.757             N/A
5 N/A                N/A               N/A
6 99.25              0.899             N/A
  closest_placement_radius closest_placement_taxonomy closest_placement_ani
1 N/A                      N/A                        N/A
2 N/A                      N/A                        N/A
3 N/A                      N/A                        N/A
4 N/A                      N/A                        N/A
5 N/A                      N/A                        N/A
6 N/A                      N/A                        N/A
  closest_placement_af pplacer_taxonomy classification_method
1 N/A                  N/A              ani_screen
2 N/A                  N/A              ani_screen
3 N/A                  N/A              ani_screen
4 N/A                  N/A              ani_screen
5 N/A                  N/A              N/A
6 N/A                  N/A              ani_screen
  note
1 classification based on ANI only
2 classification based on ANI only
3 classification based on ANI only
4 classification based on ANI only
5 N/A
6 classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCA_900764925.1, s__Fusobacterium_A sp900764925, 95.0, 87.47, 0.181; GCF_900450765.1, s__Fusobacterium_A necrogenes, 95.0, 90.82, 0.348; GCA_019410665.1, s__Fusobacterium_A sp019410665, 95.0, 87.34, 0.18; GCA_018883725.1, s__Fusobacterium_A pullicola, 95.0, 87.61, 0.226; GCF_905193685.1, s__Fusobacterium_A sp900555485, 95.0, 88.04, 0.251
2 GCF_905193685.1, s__Fusobacterium_A sp900555485, 95.0, 87.94, 0.258; GCF_900450765.1, s__Fusobacterium_A necrogenes, 95.0, 90.63, 0.353; GCA_019410665.1, s__Fusobacterium_A sp019410665, 95.0, 86.54, 0.197; GCA_018883725.1, s__Fusobacterium_A pullicola, 95.0, 86.47, 0.238; GCA_900764925.1, s__Fusobacterium_A sp900764925, 95.0, 86.64, 0.19
3 GCA_958477465.1, s__Bacteroides sp958477465, 95.0, 86.16, 0.231; GCA_963599995.1, s__Bacteroides sp963599995, 95.0, 86.39, 0.228
4 GCF_903181435.1, s__Bacteroides sp900765785, 95.0, 83.61, 0.188; GCF_024623065.1, s__Bacteroides acidifaciens, 95.0, 85.53, 0.206; GCF_028539415.1, s__Bacteroides cellulosilyticus, 95.26, 88.78, 0.29; GCA_947038155.1, s__Bacteroides sp947038155, 95.0, 84.55, 0.164; GCA_947071285.1, s__Bacteroides sp947071285, 95.0, 86.39, 0.225; GCA_900557355.1, s__Bacteroides sp900557355, 95.0, 97.31, 0.559; GCF_020091405.1, s__Bacteroides sp900552405, 95.23, 89.64, 0.32; GCA_948579315.1, s__Phocaeicola sp948579315, 95.0, 90.06, 0.234; GCA_948742525.1, s__Bacteroides caecimuris_A, 95.0, 90.02, 0.382; GCF_036416795.1, s__Bacteroides sp036416795, 95.05, 89.73, 0.345; GCF_003464595.1, s__Bacteroides intestinalis_A, 95.0, 94.35, 0.546; GCF_012113595.1, s__Bacteroides faecium, 95.0, 83.7, 0.158; GCF_900142015.1, s__Bacteroides stercorirosoris, 95.0, 85.34, 0.19; GCF_001688725.2, s__Bacteroides caecimuris, 95.89, 88.41, 0.343; GCA_948566455.1, s__Phocaeicola sp948566455, 95.0, 97.52, 0.376; GCF_000513195.1, s__Bacteroides timonensis, 95.0, 88.27, 0.284; GCA_030295565.1, s__Bacteroides finegoldii, 95.0, 86.01, 0.219; GCA_905215555.1, s__Bacteroides sp905215555, 95.0, 83.59, 0.16; GCA_019117555.1, s__Bacteroides intestinigallinarum, 95.0, 93.87, 0.595; GCA_900759525.1, s__Bacteroides sp900759525, 95.0, 87.68, 0.302; GCF_034291875.1, s__Bacteroides vicugnae, 95.0, 91.97, 0.543; GCF_009193325.2, s__Bacteroides zhangwenhongii, 95.83, 85.44, 0.191; GCF_014750685.1, s__Bacteroides sp014750685, 95.0, 83.5, 0.158; GCF_902364365.1, s__Bacteroides sp900556215, 95.07, 93.29, 0.537; GCF_000315485.1, s__Bacteroides oleiciplenus, 95.0, 84.7, 0.163; GCF_001314995.1, s__Bacteroides ovatus, 95.0, 96.8, 0.69; GCF_958387885.1, s__Bacteroides sp019412865, 95.22, 95.07, 0.662; GCA_900755095.1, s__Bacteroides sp900755095, 95.0, 97.6, 0.573; GCF_000210075.1, s__Bacteroides xylanisolvens, 95.0, 91.5, 0.517; GCF_041227145.1, s__Bacteroides sp041227145, 95.0, 86.65, 0.318; GCF_905207245.1, s__Bacteroides sp905207245, 95.0, 86.07, 0.204; GCA_900556625.1, s__Bacteroides sp900556625, 95.0, 84.52, 0.173; GCF_009193295.2, s__Bacteroides luhongzhouii, 95.0, 90.64, 0.515; GCF_900130125.1, s__Bacteroides congonensis, 95.0, 83.91, 0.182
5 N/A
6 GCA_018883725.1, s__Fusobacterium_A pullicola, 95.0, 86.26, 0.322; GCF_900450765.1, s__Fusobacterium_A necrogenes, 95.0, 89.95, 0.385; GCA_900764925.1, s__Fusobacterium_A sp900764925, 95.0, 86.48, 0.262; GCF_905193685.1, s__Fusobacterium_A sp900555485, 95.0, 86.61, 0.336; GCA_019410665.1, s__Fusobacterium_A sp019410665, 95.0, 86.76, 0.228; GCF_040199715.1, s__Fusobacterium_A sp019012925, 95.0, 82.96, 0.159
  msa_percent translation_table red_value
1 N/A         N/A               N/A
2 N/A         N/A               N/A
3 N/A         N/A               N/A
4 N/A         N/A               N/A
5 N/A         N/A               N/A
6 N/A         N/A               N/A
  warnings
1 N/A
2 N/A
3 N/A
4 N/A
5 Insufficient number of amino acids in MSA (6.4%)
6 N/A

In [5]:
# Upload result of checkm filtering

checkm_summary_atero01 <- read_delim("quality_report_bin_filtered_ID.tsv",
                                     delim = "\t", escape_double = FALSE, 
                                     trim_ws = TRUE, col_names = "user_genome")

head(checkm_summary_atero01)

Rows: 198 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): user_genome

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR2017423_N024_bin.10
2 ERR2017413_N003_bin.17
3 ERR2017414_N005_bin.2
4 ERR2017423_N024_bin.3
5 ERR2017420_N020_bin.28
6 ERR2017446_N056_bin.11

In [6]:
# Filter ID based on checkm result
gtdbtk_bac120_summary_atero01 <- semi_join(all_gtdbtk_bac120_summary_atero01, checkm_summary_atero01, by= "user_genome")


#get species name
gtdbtk_classify_atero01 <- gtdbtk_bac120_summary_atero01[,"classification"]

gtdbtk_species_atero01 <- gtdbtk_classify_atero01 %>%
  mutate(species = str_extract(classification, "(?<=s__).*"))

gtdbtk_species_atero01$species <- trimws(gtdbtk_species_atero01$species)
gtdbtk_species_atero01$species[gtdbtk_species_atero01$species == ""] <- NA

unique(gtdbtk_species_atero01$species)

 [1] "Fusobacterium_A mortiferum"      "Bacteroides salyersiae"
 [3] "Parabacteroides distasonis"      "Acetatifactor intestinalis"
 [5] "Agathobacter rectalis"           "Gemmiger formicilis"
 [7] "Paraprevotella clara"            "Lachnospira sp000437735"
 [9] "Butyricimonas virosa"            "Phocaeicola plebeius"
[11] "Phocaeicola vulgatus"            "Gemmiger sp900540775"
[13] "Fusobacterium_A pullicola"       "Lachnospira sp000436475"
[15] "Mediterraneibacter faecis"       "Eubacterium_G ventriosum"
[17] "Ruminococcoides intestinale"     "Culturomica massiliensis"
[19] "Bacteroides uniformis"           "Enterocloster bolteae"
[21] "Parabacteroides merdae"          "Citrobacter_A amalonaticus"
[23] "CAG-274 sp000432155"             "Paraprevotella xylaniphila"
[25] "Claveliimonas bilis"             "Gemmiger sp900539695"
[27] "CAG-269 sp900551615"             "Pararoseburia lenta"
[29] "Lachnospira hominis"             "Streptococcus vestibularis"
[31] "Haemophilus_D sp900756875"       "Enterocloster sp900541315"
[33] "Romboutsia timonensis"           "Gemmiger formicilis_B"
[35] "Escherichia coli"                "Thomasclavelia ramosa"
[37] "Megamonas funiformis"            "Eubacterium_U album"
[39] "Fusicatenibacter saccharivorans" "Megasphaera elsdenii"
[41] "CAG-269 sp001916005"             "Ruminococcoides bromii"
[43] "Brotaphodocola sp003481825"      "Schaedlerella hominis"
[45] "Bacteroides sp900556215"         "Collinsella sp905205405"
[47] "Fusobacterium_A sp018205345"     "Bacteroides thetaiotaomicron"
[49] "Anaerostipes hadrus"             "CAG-245 sp000435175"
[51] "Bacteroides ovatus"              "Fusobacterium_A varium"
[53] "Methanocatella smithii"

In [7]:
#count species match
table(gtdbtk_species_atero01$species)

count_gtdb_atero01 <- gtdbtk_species_atero01 %>%
  count(species, name = "occurrences")

head(count_gtdb_atero01)

     Acetatifactor intestinalis           Agathobacter rectalis
                              3                               7
            Anaerostipes hadrus              Bacteroides ovatus
                              1                               1
         Bacteroides salyersiae         Bacteroides sp900556215
                              1                               1
   Bacteroides thetaiotaomicron           Bacteroides uniformis
                              1                               4
     Brotaphodocola sp003481825            Butyricimonas virosa
                              1                               2
            CAG-245 sp000435175             CAG-269 sp001916005
                              1                               1
            CAG-269 sp900551615             CAG-274 sp000432155
                              1                               1
     Citrobacter_A amalonaticus             Claveliimonas bilis
                              1                               1
        Collinsella sp905205405        Culturomica massiliensis
                              1                               2
          Enterocloster bolteae       Enterocloster sp900541315
                              2                               1
               Escherichia coli        Eubacterium_G ventriosum
                              2                               6
            Eubacterium_U album Fusicatenibacter saccharivorans
                              1                               2
     Fusobacterium_A mortiferum       Fusobacterium_A pullicola
                             35                               2
    Fusobacterium_A sp018205345          Fusobacterium_A varium
                              1                               1
            Gemmiger formicilis           Gemmiger formicilis_B
                             61                               1
           Gemmiger sp900539695            Gemmiger sp900540775
                              9                               1
      Haemophilus_D sp900756875             Lachnospira hominis
                              1                               1
        Lachnospira sp000436475         Lachnospira sp000437735
                              1                               1
      Mediterraneibacter faecis            Megamonas funiformis
                              1                               2
           Megasphaera elsdenii          Methanocatella smithii
                              1                               2
     Parabacteroides distasonis          Parabacteroides merdae
                              5                               1
           Paraprevotella clara      Paraprevotella xylaniphila
                              9                               3
            Pararoseburia lenta            Phocaeicola plebeius
                              1                               1
           Phocaeicola vulgatus           Romboutsia timonensis
                              1                               5
         Ruminococcoides bromii     Ruminococcoides intestinale
                              1                               2
          Schaedlerella hominis      Streptococcus vestibularis
                              1                               1
          Thomasclavelia ramosa
                              1

  species                    occurrences
1 Acetatifactor intestinalis 3
2 Agathobacter rectalis      7
3 Anaerostipes hadrus        1
4 Bacteroides ovatus         1
5 Bacteroides salyersiae     1
6 Bacteroides sp900556215    1

In [8]:
unique_gtdbtk_species_atero01 <- gtdbtk_species_atero01 %>% distinct(species, .keep_all = TRUE)

unique_gtdbtk_species_atero01_ID <- unique_gtdbtk_species_atero01[,"species"]

In [ ]:
#Save output
write_tsv(unique_gtdbtk_species_atero01_ID, "GTDB_results/unique_gtdbtk_species_atero01_ID.tsv")

In [9]:
################################################################################################################
#Division of disease versus Healthy


# Remove everything after the first "-"
gtdbtk_bac120_summary_atero01$ID <- sub("_.*", "", gtdbtk_bac120_summary_atero01$user_genome)

#get ID
gtdbtk_atero01_ID_name <- gtdbtk_bac120_summary_atero01[,"ID"]

In [ ]:
#save file
write_tsv(gtdbtk_atero01_ID_name, "GTDB_results/gtdbtk_atero01_ERR_ID_name.tsv")

In [11]:
#Upload data with health and disease ID

#case
Study_1_atero_case_Run_ID <- read_csv("atero_study1_disease_ID")

head(Study_1_atero_case_Run_ID)

Rows: 214 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR2017652
2 ERR2017671
3 ERR2017810
4 ERR2017599
5 ERR2017602
6 ERR2017613

In [12]:
#control

Study_1_atero_control_Run_ID <- read_csv("atero_study1_control_ID")
head(Study_1_atero_control_Run_ID)


#match and see how many match
colnames(gtdbtk_atero01_ID_name) <- "Run"

Rows: 186 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR2017414
2 ERR2017415
3 ERR2017418
4 ERR2017419
5 ERR2017420
6 ERR2017421

In [13]:
#for case
match_atero01_case <- semi_join(gtdbtk_atero01_ID_name,Study_1_atero_case_Run_ID, by= "Run")
nrow(match_atero01_case)

#get unique IDs
match_atero01_case_unique <- match_atero01_case %>% distinct(Run)
nrow(match_atero01_case_unique)

[1] 111

[1] 89

In [14]:
#for control
match_atero01_control <- semi_join(gtdbtk_atero01_ID_name,Study_1_atero_control_Run_ID, by= "Run")
nrow(match_atero01_control)
#get unique IDs

match_atero01_control_unique <- match_atero01_control %>% distinct(Run)
nrow(match_atero01_control_unique)

[1] 85

[1] 62

In [15]:
#Final table 

cat_gtdk_ID <- merge(gtdbtk_bac120_summary_atero01,gtdbtk_species_atero01, by="classification")

cat_gtdk_ID_col <- cat_gtdk_ID[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species")]
head(cat_gtdk_ID)
nrow(cat_gtdk_ID)

  classification
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Coriobacteriaceae;g__Collinsella;s__Collinsella sp905205405
6 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Thomasclavelia;s__Thomasclavelia ramosa
  user_genome               closest_genome_reference
1 ERR2017634_ZSL-079_bin.12 GCF_000016525.1
2 ERR2017634_ZSL-079_bin.12 GCF_000016525.1
3 ERR2017729_ZSL335_bin.39  GCF_000016525.1
4 ERR2017729_ZSL335_bin.39  GCF_000016525.1
5 ERR2017711_ZSL301_bin.24  GCA_905205405.1
6 ERR2017643_ZSL-092_bin.52 GCF_014131695.1
  closest_genome_reference_radius
1 95.0
2 95.0
3 95.0
4 95.0
5 95.06
6 95.0
  closest_genome_taxonomy
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Coriobacteriaceae;g__Collinsella;s__Collinsella sp905205405
6 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Thomasclavelia;s__Thomasclavelia ramosa
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.89              0.884             N/A
2 98.89              0.884             N/A
3 98.25              0.918             N/A
4 98.25              0.918             N/A
5 95.18              0.813             N/A
6 99.75              0.857             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
6 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
6 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.81, 0.432; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.34, 0.81; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.51, 0.498
2 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.81, 0.432; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.34, 0.81; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.51, 0.498
3 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 87.0, 0.477; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.64, 0.52; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.34, 0.854
4 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 87.0, 0.477; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.64, 0.52; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.34, 0.854

[1] 5346

In [16]:
cat_gtdk_ID_unique <- cat_gtdk_ID%>% distinct(user_genome,.keep_all=TRUE)
nrow(cat_gtdk_ID_unique)
head(cat_gtdk_ID_unique)

[1] 198

  classification
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Coriobacteriaceae;g__Collinsella;s__Collinsella sp905205405
4 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Thomasclavelia;s__Thomasclavelia ramosa
5 d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Streptococcaceae;g__Streptococcus;s__Streptococcus vestibularis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__CAG-274;g__CAG-274;s__CAG-274 sp000432155
  user_genome               closest_genome_reference
1 ERR2017634_ZSL-079_bin.12 GCF_000016525.1
2 ERR2017729_ZSL335_bin.39  GCF_000016525.1
3 ERR2017711_ZSL301_bin.24  GCA_905205405.1
4 ERR2017643_ZSL-092_bin.52 GCF_014131695.1
5 ERR2017598_ZSL-004_bin.62 GCF_000188295.1
6 ERR2017558_N203_bin.63    GCA_000432155.1
  closest_genome_reference_radius
1 95.0
2 95.0
3 95.06
4 95.0
5 95.0
6 95.0
  closest_genome_taxonomy
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
3 d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Coriobacteriaceae;g__Collinsella;s__Collinsella sp905205405
4 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Thomasclavelia;s__Thomasclavelia ramosa
5 d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Streptococcaceae;g__Streptococcus;s__Streptococcus vestibularis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__CAG-274;g__CAG-274;s__CAG-274 sp000432155
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.89              0.884             N/A
2 98.25              0.918             N/A
3 95.18              0.813             N/A
4 99.75              0.857             N/A
5 96.61              0.772             N/A
6 98.97              0.858             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
6 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
6 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 86.81, 0.432; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.34, 0.81; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.51, 0.498
2 GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 87.0, 0.477; GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.64, 0.52; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.34, 0.854

In [17]:
cat_gtdk_ID_col <- cat_gtdk_ID_unique[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species", "user_genome")]


cat_atero01_preview <- merge(cat_gtdk_ID_col,count_gtdb_atero01, by= "species")
head(cat_atero01_preview)

  species
1 Acetatifactor intestinalis
2 Acetatifactor intestinalis
3 Acetatifactor intestinalis
4 Agathobacter rectalis
5 Agathobacter rectalis
6 Agathobacter rectalis
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Acetatifactor;s__Acetatifactor intestinalis
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Acetatifactor;s__Acetatifactor intestinalis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Acetatifactor;s__Acetatifactor intestinalis
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter rectalis
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter rectalis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter rectalis
  closest_genome_reference closest_genome_ani ID
1 GCF_009695995.1          96.84              ERR2017432
2 GCF_009695995.1          97.16              ERR2017588
3 GCF_009695995.1          96.76              ERR2017691
4 GCF_000020605.1          96.9               ERR2017614
5 GCF_000020605.1          97.51              ERR2017741
6 GCF_000020605.1          98.17              ERR2017660
  user_genome               occurrences
1 ERR2017432_N034_bin.17    3
2 ERR2017588_N245_bin.36    3
3 ERR2017691_ZSL265_bin.21  3
4 ERR2017614_ZSL-042_bin.16 7
5 ERR2017741_ZSL368_bin.45  7
6 ERR2017660_ZSL-123_bin.37 7

In [19]:
# handling with control and disease column

match_atero01_control$State <- "Control"
match_atero01_case$State <- "Disease"

# Change column name

colnames(match_atero01_control)[colnames(match_atero01_control) == "Run"] <- "ID"
colnames(match_atero01_case)[colnames(match_atero01_case) == "Run"] <- "ID" 

all_state <- rbind(match_atero01_control,match_atero01_case)

cat_atero01_final <- merge(cat_atero01_preview,all_state, by= "ID")
head(cat_atero01_final)
nrow(cat_atero01_final)

  ID         species
1 ERR2017413 Fusobacterium_A mortiferum
2 ERR2017414 Fusobacterium_A mortiferum
3 ERR2017420 Bacteroides salyersiae
4 ERR2017423 Parabacteroides distasonis
5 ERR2017423 Parabacteroides distasonis
6 ERR2017423 Fusobacterium_A mortiferum
  classification
1 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
2 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
3 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides salyersiae
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Tannerellaceae;g__Parabacteroides;s__Parabacteroides distasonis
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Tannerellaceae;g__Parabacteroides;s__Parabacteroides distasonis
6 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
  closest_genome_reference closest_genome_ani user_genome
1 GCF_000158195.2          99.13              ERR2017413_N003_bin.17
2 GCF_000158195.2          98.78              ERR2017414_N005_bin.2
3 GCF_000381365.1          99.29              ERR2017420_N020_bin.28
4 GCF_000012845.1          98.52              ERR2017423_N024_bin.3
5 GCF_000012845.1          98.52              ERR2017423_N024_bin.3
6 GCF_000158195.2          99.25              ERR2017423_N024_bin.10
  occurrences State
1 35          Control
2 35          Control
3  1          Control
4  5          Control
5  5          Control
6 35          Control

[1] 300

In [20]:
cat_atero01_final_end <- cat_atero01_final %>% distinct(user_genome, .keep_all = TRUE)
head(cat_atero01_final_end)
nrow(cat_atero01_final_end)

  ID         species
1 ERR2017413 Fusobacterium_A mortiferum
2 ERR2017414 Fusobacterium_A mortiferum
3 ERR2017420 Bacteroides salyersiae
4 ERR2017423 Parabacteroides distasonis
5 ERR2017423 Fusobacterium_A mortiferum
6 ERR2017432 Acetatifactor intestinalis
  classification
1 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
2 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
3 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides salyersiae
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Tannerellaceae;g__Parabacteroides;s__Parabacteroides distasonis
5 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Acetatifactor;s__Acetatifactor intestinalis
  closest_genome_reference closest_genome_ani user_genome
1 GCF_000158195.2          99.13              ERR2017413_N003_bin.17
2 GCF_000158195.2          98.78              ERR2017414_N005_bin.2
3 GCF_000381365.1          99.29              ERR2017420_N020_bin.28
4 GCF_000012845.1          98.52              ERR2017423_N024_bin.3
5 GCF_000158195.2          99.25              ERR2017423_N024_bin.10
6 GCF_009695995.1          96.84              ERR2017432_N034_bin.17
  occurrences State
1 35          Control
2 35          Control
3  1          Control
4  5          Control
5 35          Control
6  3          Control

[1] 196

In [ ]:
write_tsv(cat_atero01_final_end, "GTDB_results/final_table_gtdb_for_paper_atero01.tsv")
write_tsv(count_gtdb_atero01, "GTDB_results/species_occurrence.tsv")

In [22]:
# Classify species
classification <- cat_atero01_final_end %>%
  filter(!is.na(species), !is.na(State)) %>%
  group_by(species) %>%
  summarise(
    Group_classification = case_when(
      n_distinct(State) == 1 & first(State) == "Disease" ~ "Disease",
      n_distinct(State) == 1 & first(State) == "Control" ~ "Control",
      n_distinct(State) > 1 ~ "Control/Disease"
    ),
    .groups = "drop"
  )

# Join  and apply rule for Species == NA
cat_atero01_final_end_df <- cat_atero01_final_end %>%
  left_join(classification, by = "species") %>%
  mutate(
    Group_classification = ifelse(
      is.na(species),
      State,
      Group_classification
    )
  )

head(cat_atero01_final_end_df)

  ID         species
1 ERR2017413 Fusobacterium_A mortiferum
2 ERR2017414 Fusobacterium_A mortiferum
3 ERR2017420 Bacteroides salyersiae
4 ERR2017423 Parabacteroides distasonis
5 ERR2017423 Fusobacterium_A mortiferum
6 ERR2017432 Acetatifactor intestinalis
  classification
1 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
2 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
3 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides salyersiae
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Tannerellaceae;g__Parabacteroides;s__Parabacteroides distasonis
5 d__Bacteria;p__Fusobacteriota;c__Fusobacteriia;o__Fusobacteriales;f__Fusobacteriaceae;g__Fusobacterium_A;s__Fusobacterium_A mortiferum
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Acetatifactor;s__Acetatifactor intestinalis
  closest_genome_reference closest_genome_ani user_genome
1 GCF_000158195.2          99.13              ERR2017413_N003_bin.17
2 GCF_000158195.2          98.78              ERR2017414_N005_bin.2
3 GCF_000381365.1          99.29              ERR2017420_N020_bin.28
4 GCF_000012845.1          98.52              ERR2017423_N024_bin.3
5 GCF_000158195.2          99.25              ERR2017423_N024_bin.10
6 GCF_009695995.1          96.84              ERR2017432_N034_bin.17
  occurrences State   Group_classification
1 35          Control Control/Disease
2 35          Control Control/Disease
3  1          Control Control
4  5          Control Control/Disease
5 35          Control Control/Disease
6  3          Control Control/Disease

In [ ]:
write_tsv(cat_atero01_final_end_df,"GTDB_results/gtdb_final_table_with_condition_atero01_corrected.tsv")

In [24]:
cat_atero01_final_end_df_col <- cat_atero01_final_end_df[ ,c("species", "occurrences", "Group_classification")]

cat_atero01_final_end_df_col_unique <- cat_atero01_final_end_df_col %>% distinct(species, .keep_all = TRUE)

In [25]:
# Output table for final paper
head(cat_atero01_final_end_df_col_unique)
nrow(cat_atero01_final_end_df_col_unique)

  species                    occurrences Group_classification
1 Fusobacterium_A mortiferum 35          Control/Disease
2 Bacteroides salyersiae      1          Control
3 Parabacteroides distasonis  5          Control/Disease
4 Acetatifactor intestinalis  3          Control/Disease
5 Agathobacter rectalis       7          Control/Disease
6 Gemmiger formicilis        61          Control/Disease

[1] 53

In [ ]:
write_tsv(cat_atero01_final_end_df_col_unique, "GTDB_results/count_ocurrence_w_condition_for_paper_atero01.tsv")